<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Errors;

class ConflictExceptionThrowable extends \RuntimeException
{
    public ConflictException $container;

    public function __construct(string $message, int $statusCode, ConflictException $container)
    {
        parent::__construct($message, $statusCode);
        $this->container = $container;
    }
}