<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Errors;

use Midday\Midday\Utils;
/** GetInboxPreSignedUrlBadRequestException - Bad request - Attachment file path not available */
class GetInboxPreSignedUrlBadRequestException
{
    /**
     *
     * @var string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    public string $error;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;

    /**
     * @param  string  $error
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @phpstan-pure
     */
    public function __construct(string $error, ?\Psr\Http\Message\ResponseInterface $rawResponse = null)
    {
        $this->error = $error;
        $this->rawResponse = $rawResponse;
    }

    public function toException(): GetInboxPreSignedUrlBadRequestExceptionThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new GetInboxPreSignedUrlBadRequestExceptionThrowable($message, (int) $code, $this);
    }
}