<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Errors;

use Midday\Midday\Utils;
/** PostOAuthTokenBadRequestException - Invalid request */
class PostOAuthTokenBadRequestException
{
    /**
     * Error code
     *
     * @var string $error
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error')]
    public string $error;

    /**
     * Human-readable error description
     *
     * @var ?string $errorDescription
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error_description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $errorDescription = null;

    /**
     * URI to a human-readable error page
     *
     * @var ?string $errorUri
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('error_uri')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $errorUri = null;

    /**
     * State parameter from the original request (min 32 chars, alphanumeric + _.-)
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;

    /**
     * @param  string  $error
     * @param  ?string  $errorDescription
     * @param  ?string  $errorUri
     * @param  ?string  $state
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @phpstan-pure
     */
    public function __construct(string $error, ?string $errorDescription = null, ?string $errorUri = null, ?string $state = null, ?\Psr\Http\Message\ResponseInterface $rawResponse = null)
    {
        $this->error = $error;
        $this->errorDescription = $errorDescription;
        $this->errorUri = $errorUri;
        $this->state = $state;
        $this->rawResponse = $rawResponse;
    }

    public function toException(): PostOAuthTokenBadRequestExceptionThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new PostOAuthTokenBadRequestExceptionThrowable($message, (int) $code, $this);
    }
}