<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Errors;

use Midday\Midday\Utils;
/** UnauthorizedException - Unauthorized */
class UnauthorizedException
{
    /**
     *
     * @var string $redirectUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('redirect_url')]
    public string $redirectUrl;

    /**
     * Raw HTTP response; suitable for custom response parsing
     *
     * @var ?\Psr\Http\Message\ResponseInterface $rawResponse
     */
    #[\Speakeasy\Serializer\Annotation\Exclude]

    public ?\Psr\Http\Message\ResponseInterface $rawResponse = null;

    /**
     * @param  string  $redirectUrl
     * @param  ?\Psr\Http\Message\ResponseInterface  $rawResponse
     * @phpstan-pure
     */
    public function __construct(string $redirectUrl, ?\Psr\Http\Message\ResponseInterface $rawResponse = null)
    {
        $this->redirectUrl = $redirectUrl;
        $this->rawResponse = $rawResponse;
    }

    public function toException(): UnauthorizedExceptionThrowable
    {
        $serializer = Utils\JSON::createSerializer();
        $message = $serializer->serialize($this, 'json');
        $code = -1;

        return new UnauthorizedExceptionThrowable($message, (int) $code, $this);
    }
}