<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** BottomBlock - Custom content block to display at the bottom of the invoice in TipTap JSONContent format */
class BottomBlock
{

    public function __construct()
    {
    }
}