<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** CreateInvoiceResponseBody - Response after creating a draft invoice */
class CreateInvoiceResponseBody
{
    /**
     * Unique identifier for the draft invoice
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Current status of the invoice
     *
     * @var CreateInvoiceStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\CreateInvoiceStatus')]
    public CreateInvoiceStatus $status;

    /**
     * Timestamp when the invoice was created (ISO 8601)
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     * Timestamp when the invoice was last updated (ISO 8601)
     *
     * @var string $updatedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('updatedAt')]
    public string $updatedAt;

    /**
     * Direct URL to download the invoice PDF
     *
     * @var ?string $pdfUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('pdfUrl')]
    public ?string $pdfUrl;

    /**
     * Direct URL to preview the invoice in browser
     *
     * @var ?string $previewUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('previewUrl')]
    public ?string $previewUrl;

    /**
     * @param  string  $id
     * @param  CreateInvoiceStatus  $status
     * @param  string  $createdAt
     * @param  string  $updatedAt
     * @param  ?string  $pdfUrl
     * @param  ?string  $previewUrl
     * @phpstan-pure
     */
    public function __construct(string $id, CreateInvoiceStatus $status, string $createdAt, string $updatedAt, ?string $pdfUrl = null, ?string $previewUrl = null)
    {
        $this->id = $id;
        $this->status = $status;
        $this->createdAt = $createdAt;
        $this->updatedAt = $updatedAt;
        $this->pdfUrl = $pdfUrl;
        $this->previewUrl = $previewUrl;
    }
}