<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class CreateCustomerRequest
{
    /**
     * Name of the customer or organization
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Primary email address of the customer
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     * Unique identifier of the customer. Required for updates, omit for new customers
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * Array of tags to associate with the customer for categorization
     *
     * @var ?array<CreateCustomerTagRequest> $tags
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tags')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Operations\CreateCustomerTagRequest>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $tags = null;

    /**
     * Billing email address of the customer
     *
     * @var ?string $billingEmail
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billingEmail')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $billingEmail = null;

    /**
     * Country name where the customer is located
     *
     * @var ?string $country
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('country')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $country = null;

    /**
     * First line of the customer's address
     *
     * @var ?string $addressLine1
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addressLine1')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $addressLine1 = null;

    /**
     * Second line of the customer's address (suite, apartment, etc.)
     *
     * @var ?string $addressLine2
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('addressLine2')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $addressLine2 = null;

    /**
     * City where the customer is located
     *
     * @var ?string $city
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('city')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $city = null;

    /**
     * State or province where the customer is located
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     * ZIP or postal code of the customer's address
     *
     * @var ?string $zip
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('zip')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $zip = null;

    /**
     * Primary phone number of the customer
     *
     * @var ?string $phone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('phone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $phone = null;

    /**
     * Website URL of the customer
     *
     * @var ?string $website
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('website')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $website = null;

    /**
     * Internal notes about the customer for team reference
     *
     * @var ?string $note
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('note')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $note = null;

    /**
     * VAT (Value Added Tax) number of the customer
     *
     * @var ?string $vatNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('vatNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $vatNumber = null;

    /**
     * Country code in ISO 3166-1 alpha-2 format
     *
     * @var ?string $countryCode
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('countryCode')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $countryCode = null;

    /**
     * Primary contact person's name at the customer organization
     *
     * @var ?string $contact
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contact')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $contact = null;

    /**
     * @param  string  $name
     * @param  string  $email
     * @param  ?string  $id
     * @param  ?array<CreateCustomerTagRequest>  $tags
     * @param  ?string  $billingEmail
     * @param  ?string  $country
     * @param  ?string  $addressLine1
     * @param  ?string  $addressLine2
     * @param  ?string  $city
     * @param  ?string  $state
     * @param  ?string  $zip
     * @param  ?string  $phone
     * @param  ?string  $website
     * @param  ?string  $note
     * @param  ?string  $vatNumber
     * @param  ?string  $countryCode
     * @param  ?string  $contact
     * @phpstan-pure
     */
    public function __construct(string $name, string $email, ?string $id = null, ?array $tags = null, ?string $billingEmail = null, ?string $country = null, ?string $addressLine1 = null, ?string $addressLine2 = null, ?string $city = null, ?string $state = null, ?string $zip = null, ?string $phone = null, ?string $website = null, ?string $note = null, ?string $vatNumber = null, ?string $countryCode = null, ?string $contact = null)
    {
        $this->name = $name;
        $this->email = $email;
        $this->id = $id;
        $this->tags = $tags;
        $this->billingEmail = $billingEmail;
        $this->country = $country;
        $this->addressLine1 = $addressLine1;
        $this->addressLine2 = $addressLine2;
        $this->city = $city;
        $this->state = $state;
        $this->zip = $zip;
        $this->phone = $phone;
        $this->website = $website;
        $this->note = $note;
        $this->vatNumber = $vatNumber;
        $this->countryCode = $countryCode;
        $this->contact = $contact;
    }
}