<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** Current status of the project */
enum CreateTrackerProjectStatus: string
{
    case InProgress = 'in_progress';
    case Completed = 'completed';
}
