<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** CreateInvoiceRequest - Schema for creating an invoice. The deliveryType determines if it stays as a draft, gets finalized immediately, or gets scheduled for later processing. */
class CreateInvoiceRequest
{
    /**
     * Invoice template details
     *
     * @var Template $template
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('template')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\Template')]
    public Template $template;

    /**
     * Unique identifier for the customer (required)
     *
     * @var string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customerId')]
    public string $customerId;

    /**
     * Due date of the invoice in ISO 8601 format
     *
     * @var string $dueDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dueDate')]
    public string $dueDate;

    /**
     * Issue date of the invoice in ISO 8601 format
     *
     * @var string $issueDate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('issueDate')]
    public string $issueDate;

    /**
     * How the invoice should be processed: 'create' - finalize immediately, 'create_and_send' - finalize and send to customer, 'scheduled' - schedule for automatic processing at specified date
     *
     * @var DeliveryType $deliveryType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\DeliveryType')]
    public DeliveryType $deliveryType;

    /**
     * Sender details in TipTap JSONContent format
     *
     * @var ?FromDetails $fromDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fromDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\FromDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?FromDetails $fromDetails = null;

    /**
     * Payment details in TipTap JSONContent format
     *
     * @var ?PaymentDetails $paymentDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\PaymentDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?PaymentDetails $paymentDetails = null;

    /**
     * Additional notes for the invoice in TipTap JSONContent format
     *
     * @var ?NoteDetails $noteDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('noteDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\NoteDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?NoteDetails $noteDetails = null;

    /**
     * Invoice number as shown to the customer (auto-generated if not provided)
     *
     * @var ?string $invoiceNumber
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoiceNumber')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $invoiceNumber = null;

    /**
     * Custom content block to display at the top of the invoice in TipTap JSONContent format
     *
     * @var ?TopBlock $topBlock
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('topBlock')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\TopBlock|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TopBlock $topBlock = null;

    /**
     * Custom content block to display at the bottom of the invoice in TipTap JSONContent format
     *
     * @var ?BottomBlock $bottomBlock
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('bottomBlock')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\BottomBlock|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?BottomBlock $bottomBlock = null;

    /**
     * List of line items for the invoice
     *
     * @var ?array<LineItem> $lineItems
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lineItems')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Operations\LineItem>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $lineItems = null;

    /**
     * Scheduled date of the invoice in ISO 8601 format. Required when deliveryType is 'scheduled'. Must be in the future.
     *
     * @var ?\DateTime $scheduledAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scheduledAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $scheduledAt = null;

    /**
     * URL of the logo to display on the invoice
     *
     * @var ?string $logoUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logoUrl')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $logoUrl = null;

    /**
     * VAT amount for the invoice
     *
     * @var ?float $vat
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('vat')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $vat = null;

    /**
     * Tax amount for the invoice
     *
     * @var ?float $tax
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $tax = null;

    /**
     * Discount applied to the invoice
     *
     * @var ?float $discount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $discount = null;

    /**
     * Total amount of the invoice
     *
     * @var ?float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $amount = null;

    /**
     * @param  Template  $template
     * @param  string  $customerId
     * @param  string  $dueDate
     * @param  string  $issueDate
     * @param  DeliveryType  $deliveryType
     * @param  ?FromDetails  $fromDetails
     * @param  ?PaymentDetails  $paymentDetails
     * @param  ?NoteDetails  $noteDetails
     * @param  ?string  $invoiceNumber
     * @param  ?TopBlock  $topBlock
     * @param  ?BottomBlock  $bottomBlock
     * @param  ?array<LineItem>  $lineItems
     * @param  ?\DateTime  $scheduledAt
     * @param  ?string  $logoUrl
     * @param  ?float  $vat
     * @param  ?float  $tax
     * @param  ?float  $discount
     * @param  ?float  $amount
     * @phpstan-pure
     */
    public function __construct(Template $template, string $customerId, string $dueDate, string $issueDate, DeliveryType $deliveryType, ?FromDetails $fromDetails = null, ?PaymentDetails $paymentDetails = null, ?NoteDetails $noteDetails = null, ?string $invoiceNumber = null, ?TopBlock $topBlock = null, ?BottomBlock $bottomBlock = null, ?array $lineItems = null, ?\DateTime $scheduledAt = null, ?string $logoUrl = null, ?float $vat = null, ?float $tax = null, ?float $discount = null, ?float $amount = null)
    {
        $this->template = $template;
        $this->customerId = $customerId;
        $this->dueDate = $dueDate;
        $this->issueDate = $issueDate;
        $this->deliveryType = $deliveryType;
        $this->fromDetails = $fromDetails;
        $this->paymentDetails = $paymentDetails;
        $this->noteDetails = $noteDetails;
        $this->invoiceNumber = $invoiceNumber;
        $this->topBlock = $topBlock;
        $this->bottomBlock = $bottomBlock;
        $this->lineItems = $lineItems;
        $this->scheduledAt = $scheduledAt;
        $this->logoUrl = $logoUrl;
        $this->vat = $vat;
        $this->tax = $tax;
        $this->discount = $discount;
        $this->amount = $amount;
    }
}