<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** CreateBankAccountRequest - Schema for creating a new bank account. */
class CreateBankAccountRequest
{
    /**
     * The name of the bank account.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * The currency code for the bank account (ISO 4217).
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     * Whether the bank account is a manual account.
     *
     * @var ?bool $manual
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('manual')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $manual = null;

    /**
     * @param  string  $name
     * @param  ?string  $currency
     * @param  ?bool  $manual
     * @phpstan-pure
     */
    public function __construct(string $name, ?string $currency = null, ?bool $manual = null)
    {
        $this->name = $name;
        $this->currency = $currency;
        $this->manual = $manual;
    }
}