<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class CreateTrackerEntriesBulkRequest
{
    /**
     * Array of tracker entries to create (maximum 100 entries per request)
     *
     * @var array<Entry> $entries
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('entries')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Operations\Entry>')]
    public array $entries;

    /**
     * @param  array<Entry>  $entries
     * @phpstan-pure
     */
    public function __construct(array $entries)
    {
        $this->entries = $entries;
    }
}