<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class CreateTransactionsAttachment
{
    /**
     * Path(s) of the attachment file(s).
     *
     * @var array<string> $path
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('path')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $path;

    /**
     * Name of the attachment file.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Size of the attachment file in bytes.
     *
     * @var float $size
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('size')]
    public float $size;

    /**
     * MIME type of the attachment file.
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * @param  array<string>  $path
     * @param  string  $name
     * @param  float  $size
     * @param  string  $type
     * @phpstan-pure
     */
    public function __construct(array $path, string $name, float $size, string $type)
    {
        $this->path = $path;
        $this->name = $name;
        $this->size = $size;
        $this->type = $type;
    }
}