<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** CurrentEntry - Current running timer details, null if not running */
class CurrentEntry
{
    /**
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     *
     * @var string $projectId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('projectId')]
    public string $projectId;

    /**
     *
     * @var TrackerProject $trackerProject
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('trackerProject')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\TrackerProject')]
    public TrackerProject $trackerProject;

    /**
     *
     * @var ?string $start
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start')]
    public ?string $start;

    /**
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public ?string $description;

    /**
     * @param  string  $id
     * @param  string  $projectId
     * @param  TrackerProject  $trackerProject
     * @param  ?string  $start
     * @param  ?string  $description
     * @phpstan-pure
     */
    public function __construct(string $id, string $projectId, TrackerProject $trackerProject, ?string $start = null, ?string $description = null)
    {
        $this->id = $id;
        $this->projectId = $projectId;
        $this->trackerProject = $trackerProject;
        $this->start = $start;
        $this->description = $description;
    }
}