<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** User's authorization decision */
enum Decision: string
{
    case Allow = 'allow';
    case Deny = 'deny';
}
