<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** GetBankAccountByIdResponseBody - A single bank account object response. */
class GetBankAccountByIdResponseBody
{
    /**
     * Unique identifier for the bank account.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Whether the bank account is enabled.
     *
     * @var bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    public bool $enabled;

    /**
     * Name of the bank account.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public ?string $name;

    /**
     * Currency code of the bank account (e.g., USD, EUR).
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public ?string $currency;

    /**
     * Type of the bank account (e.g., depository, credit).
     *
     * @var ?string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public ?string $type;

    /**
     * Current balance of the bank account.
     *
     * @var ?float $balance
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('balance')]
    public ?float $balance;

    /**
     * Whether the bank account is a manual account.
     *
     * @var ?bool $manual
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('manual')]
    public ?bool $manual;

    /**
     * @param  string  $id
     * @param  bool  $enabled
     * @param  ?string  $name
     * @param  ?string  $currency
     * @param  ?string  $type
     * @param  ?float  $balance
     * @param  ?bool  $manual
     * @phpstan-pure
     */
    public function __construct(string $id, bool $enabled, ?string $name = null, ?string $currency = null, ?string $type = null, ?float $balance = null, ?bool $manual = null)
    {
        $this->id = $id;
        $this->enabled = $enabled;
        $this->name = $name;
        $this->currency = $currency;
        $this->type = $type;
        $this->balance = $balance;
        $this->manual = $manual;
    }
}