<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class GetCurrentTimerData
{
    /**
     * Unique identifier of the tracker entry
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Date and time when the tracker entry was created in ISO 8601 format
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     * Start time of the tracker entry in ISO 8601 format
     *
     * @var string $start
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('start')]
    public string $start;

    /**
     * Stop time of the tracker entry in ISO 8601 format
     *
     * @var string $stop
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('stop')]
    public string $stop;

    /**
     * Unique identifier of the team that owns this tracker entry
     *
     * @var string $teamId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('teamId')]
    public string $teamId;

    /**
     * Whether this tracker entry has been billed to the customer
     *
     * @var bool $billed
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billed')]
    public bool $billed;

    /**
     * Date of the tracker entry in YYYY-MM-DD format
     *
     * @var string $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public string $date;

    /**
     * User information for the person who created this tracker entry
     *
     * @var GetCurrentTimerUser $user
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('user')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\GetCurrentTimerUser')]
    public GetCurrentTimerUser $user;

    /**
     * Project information associated with this tracker entry
     *
     * @var GetCurrentTimerProject $project
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('project')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\GetCurrentTimerProject')]
    public GetCurrentTimerProject $project;

    /**
     * Duration of the timer entry in seconds. -1 indicates running, null for paused, positive number for completed
     *
     * @var ?float $duration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('duration')]
    public ?float $duration;

    /**
     * Description or notes for the tracker entry
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public ?string $description;

    /**
     * Hourly rate applied to this tracker entry
     *
     * @var ?float $rate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rate')]
    public ?float $rate;

    /**
     * Currency code for the rate in ISO 4217 format
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public ?string $currency;

    /**
     * @param  string  $id
     * @param  string  $createdAt
     * @param  string  $start
     * @param  string  $stop
     * @param  string  $teamId
     * @param  bool  $billed
     * @param  string  $date
     * @param  GetCurrentTimerUser  $user
     * @param  GetCurrentTimerProject  $project
     * @param  ?float  $duration
     * @param  ?string  $description
     * @param  ?float  $rate
     * @param  ?string  $currency
     * @phpstan-pure
     */
    public function __construct(string $id, string $createdAt, string $start, string $stop, string $teamId, bool $billed, string $date, GetCurrentTimerUser $user, GetCurrentTimerProject $project, ?float $duration = null, ?string $description = null, ?float $rate = null, ?string $currency = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->start = $start;
        $this->stop = $stop;
        $this->teamId = $teamId;
        $this->billed = $billed;
        $this->date = $date;
        $this->user = $user;
        $this->project = $project;
        $this->duration = $duration;
        $this->description = $description;
        $this->rate = $rate;
        $this->currency = $currency;
    }
}