<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class GetDocumentPreSignedUrlRequest
{
    /**
     *
     * @var string $id
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;

    /**
     *
     * @var ?bool $download
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=download')]
    public ?bool $download = null;

    /**
     * @param  string  $id
     * @param  ?bool  $download
     * @phpstan-pure
     */
    public function __construct(string $id, ?bool $download = null)
    {
        $this->id = $id;
        $this->download = $download;
    }
}