<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** GetDocumentByIdMetadata - Metadata about the document. */
class GetDocumentByIdMetadata
{
    /**
     * Size of the document in bytes.
     *
     * @var ?float $size
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('size')]
    public ?float $size;

    /**
     * MIME type of the document.
     *
     * @var ?string $mimetype
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('mimetype')]
    public ?string $mimetype;

    /**
     * @param  ?float  $size
     * @param  ?string  $mimetype
     * @phpstan-pure
     */
    public function __construct(?float $size = null, ?string $mimetype = null)
    {
        $this->size = $size;
        $this->mimetype = $mimetype;
    }
}