<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class GetInvoiceSummaryRequest
{
    /**
     * Filter summary by invoice status
     *
     * @var ?GetInvoiceSummaryStatus $status
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?GetInvoiceSummaryStatus $status = null;

    /**
     * @param  ?GetInvoiceSummaryStatus  $status
     * @phpstan-pure
     */
    public function __construct(?GetInvoiceSummaryStatus $status = null)
    {
        $this->status = $status;
    }
}