<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** GetInboxItemByIdTransaction - Matched transaction for this inbox item, if any */
class GetInboxItemByIdTransaction
{
    /**
     * Transaction ID (UUID)
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Transaction amount
     *
     * @var float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public float $amount;

    /**
     * Transaction currency (ISO 4217)
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * Transaction name or payee
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Transaction date (ISO 8601)
     *
     * @var string $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public string $date;

    /**
     * @param  string  $id
     * @param  float  $amount
     * @param  string  $currency
     * @param  string  $name
     * @param  string  $date
     * @phpstan-pure
     */
    public function __construct(string $id, float $amount, string $currency, string $name, string $date)
    {
        $this->id = $id;
        $this->amount = $amount;
        $this->currency = $currency;
        $this->name = $name;
        $this->date = $date;
    }
}