<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** Current status of the invoice */
enum GetInvoiceByIdStatus: string
{
    case Draft = 'draft';
    case Overdue = 'overdue';
    case Paid = 'paid';
    case Unpaid = 'unpaid';
    case Canceled = 'canceled';
}
