<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** GetInvoicesPaymentStatusResponseBody - Payment status for the authenticated team. */
class GetInvoicesPaymentStatusResponseBody
{
    /**
     * Score associated with the invoice payment status
     *
     * @var float $score
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('score')]
    public float $score;

    /**
     * The payment status of the invoice
     *
     * @var string $paymentStatus
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentStatus')]
    public string $paymentStatus;

    /**
     * @param  float  $score
     * @param  string  $paymentStatus
     * @phpstan-pure
     */
    public function __construct(float $score, string $paymentStatus)
    {
        $this->score = $score;
        $this->paymentStatus = $paymentStatus;
    }
}