<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** GetInvoiceByIdCustomer - Customer details */
class GetInvoiceByIdCustomer
{
    /**
     * Unique identifier for the customer
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Name of the customer
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Website URL of the customer
     *
     * @var ?string $website
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('website')]
    public ?string $website;

    /**
     * Email address of the customer
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public ?string $email;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  ?string  $website
     * @param  ?string  $email
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, ?string $website = null, ?string $email = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->website = $website;
        $this->email = $email;
    }
}