<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** GetInboxItemByIdResponseBody - Inbox item object */
class GetInboxItemByIdResponseBody
{
    /**
     * Inbox item ID (UUID)
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Original file name of the uploaded document
     *
     * @var string $fileName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fileName')]
    public string $fileName;

    /**
     * Path segments to the file in storage
     *
     * @var array<string> $filePath
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('filePath')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $filePath;

    /**
     * Display name for the inbox item
     *
     * @var string $displayName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('displayName')]
    public string $displayName;

    /**
     * Status of the inbox item
     *
     * @var string $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    public string $status;

    /**
     * Date and time when the inbox item was created (ISO 8601)
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     * Amount detected or entered for the inbox item
     *
     * @var ?float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public ?float $amount;

    /**
     * Currency code (ISO 4217) for the amount
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public ?string $currency;

    /**
     * MIME type of the uploaded file
     *
     * @var ?string $contentType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('contentType')]
    public ?string $contentType;

    /**
     * Date associated with the inbox item (ISO 8601)
     *
     * @var ?string $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public ?string $date;

    /**
     * Website associated with the inbox item, if any
     *
     * @var ?string $website
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('website')]
    public ?string $website;

    /**
     * Description or notes for the inbox item
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public ?string $description;

    /**
     * Matched transaction for this inbox item, if any
     *
     * @var ?GetInboxItemByIdTransaction $transaction
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('transaction')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\GetInboxItemByIdTransaction|null')]
    public ?GetInboxItemByIdTransaction $transaction;

    /**
     * @param  string  $id
     * @param  string  $fileName
     * @param  array<string>  $filePath
     * @param  string  $displayName
     * @param  string  $status
     * @param  string  $createdAt
     * @param  ?float  $amount
     * @param  ?string  $currency
     * @param  ?string  $contentType
     * @param  ?string  $date
     * @param  ?string  $website
     * @param  ?string  $description
     * @param  ?GetInboxItemByIdTransaction  $transaction
     * @phpstan-pure
     */
    public function __construct(string $id, string $fileName, array $filePath, string $displayName, string $status, string $createdAt, ?float $amount = null, ?string $currency = null, ?string $contentType = null, ?string $date = null, ?string $website = null, ?string $description = null, ?GetInboxItemByIdTransaction $transaction = null)
    {
        $this->id = $id;
        $this->fileName = $fileName;
        $this->filePath = $filePath;
        $this->displayName = $displayName;
        $this->status = $status;
        $this->createdAt = $createdAt;
        $this->amount = $amount;
        $this->currency = $currency;
        $this->contentType = $contentType;
        $this->date = $date;
        $this->website = $website;
        $this->description = $description;
        $this->transaction = $transaction;
    }
}