<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class GetOAuthAuthorizationRequest
{
    /**
     * OAuth response type, must be 'code'
     *
     * @var ResponseType $responseType
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=response_type')]
    public ResponseType $responseType;

    /**
     *
     * @var string $clientId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=client_id')]
    public string $clientId;

    /**
     *
     * @var string $redirectUri
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=redirect_uri')]
    public string $redirectUri;

    /**
     *
     * @var string $scope
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=scope')]
    public string $scope;

    /**
     *
     * @var string $state
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=state')]
    public string $state;

    /**
     *
     * @var ?string $codeChallenge
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=code_challenge')]
    public ?string $codeChallenge = null;

    /**
     * @param  ResponseType  $responseType
     * @param  string  $clientId
     * @param  string  $redirectUri
     * @param  string  $scope
     * @param  string  $state
     * @param  ?string  $codeChallenge
     * @phpstan-pure
     */
    public function __construct(ResponseType $responseType, string $clientId, string $redirectUri, string $scope, string $state, ?string $codeChallenge = null)
    {
        $this->responseType = $responseType;
        $this->clientId = $clientId;
        $this->redirectUri = $redirectUri;
        $this->scope = $scope;
        $this->state = $state;
        $this->codeChallenge = $codeChallenge;
    }
}