<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** GetOAuthAuthorizationResponseBody - Application information for consent screen */
class GetOAuthAuthorizationResponseBody
{
    /**
     * Application ID
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Application name
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Up to 4 screenshots that will be displayed on the apps page
     *
     * @var array<string> $screenshots
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('screenshots')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $screenshots;

    /**
     * Client ID
     *
     * @var string $clientId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('clientId')]
    public string $clientId;

    /**
     * Requested scopes
     *
     * @var array<string> $scopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scopes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $scopes;

    /**
     * Redirect URI
     *
     * @var string $redirectUri
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('redirectUri')]
    public string $redirectUri;

    /**
     * Application verification status
     *
     * @var GetOAuthAuthorizationStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\GetOAuthAuthorizationStatus')]
    public GetOAuthAuthorizationStatus $status;

    /**
     * Application description
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public ?string $description;

    /**
     * Application overview
     *
     * @var ?string $overview
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('overview')]
    public ?string $overview;

    /**
     * The person or company developing this application
     *
     * @var ?string $developerName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('developerName')]
    public ?string $developerName;

    /**
     * Application logo URL
     *
     * @var ?string $logoUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logoUrl')]
    public ?string $logoUrl;

    /**
     * Application website
     *
     * @var ?string $website
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('website')]
    public ?string $website;

    /**
     * An optional URL for installing the application
     *
     * @var ?string $installUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('installUrl')]
    public ?string $installUrl;

    /**
     * State parameter (min 32 chars, alphanumeric + _.-)
     *
     * @var ?string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $state = null;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  array<string>  $screenshots
     * @param  string  $clientId
     * @param  array<string>  $scopes
     * @param  string  $redirectUri
     * @param  GetOAuthAuthorizationStatus  $status
     * @param  ?string  $description
     * @param  ?string  $overview
     * @param  ?string  $developerName
     * @param  ?string  $logoUrl
     * @param  ?string  $website
     * @param  ?string  $installUrl
     * @param  ?string  $state
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, array $screenshots, string $clientId, array $scopes, string $redirectUri, GetOAuthAuthorizationStatus $status, ?string $description = null, ?string $overview = null, ?string $developerName = null, ?string $logoUrl = null, ?string $website = null, ?string $installUrl = null, ?string $state = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->screenshots = $screenshots;
        $this->clientId = $clientId;
        $this->scopes = $scopes;
        $this->redirectUri = $redirectUri;
        $this->status = $status;
        $this->description = $description;
        $this->overview = $overview;
        $this->developerName = $developerName;
        $this->logoUrl = $logoUrl;
        $this->website = $website;
        $this->installUrl = $installUrl;
        $this->state = $state;
    }
}