<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** GetTransactionAttachmentPreSignedUrlResponseBody - Pre-signed URL generated successfully */
class GetTransactionAttachmentPreSignedUrlResponseBody
{
    /**
     * Pre-signed URL for accessing the attachment, valid for 60 seconds
     *
     * @var string $url
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('url')]
    public string $url;

    /**
     * ISO 8601 timestamp when the URL expires
     *
     * @var \DateTime $expiresAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expiresAt')]
    public \DateTime $expiresAt;

    /**
     * Original filename of the attachment
     *
     * @var ?string $fileName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fileName')]
    public ?string $fileName;

    /**
     * @param  string  $url
     * @param  \DateTime  $expiresAt
     * @param  ?string  $fileName
     * @phpstan-pure
     */
    public function __construct(string $url, \DateTime $expiresAt, ?string $fileName = null)
    {
        $this->url = $url;
        $this->expiresAt = $expiresAt;
        $this->fileName = $fileName;
    }
}