<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class GetTimerStatusRequest
{
    /**
     *
     * @var ?string $assignedId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=assignedId')]
    public ?string $assignedId = null;

    /**
     * @param  ?string  $assignedId
     * @phpstan-pure
     */
    public function __construct(?string $assignedId = null)
    {
        $this->assignedId = $assignedId;
    }
}