<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class GetTransactionAttachmentPreSignedUrlRequest
{
    /**
     *
     * @var string $transactionId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=transactionId')]
    public string $transactionId;

    /**
     *
     * @var string $attachmentId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=attachmentId')]
    public string $attachmentId;

    /**
     *
     * @var ?bool $download
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=download')]
    public ?bool $download = null;

    /**
     * @param  string  $transactionId
     * @param  string  $attachmentId
     * @param  ?bool  $download
     * @phpstan-pure
     */
    public function __construct(string $transactionId, string $attachmentId, ?bool $download = null)
    {
        $this->transactionId = $transactionId;
        $this->attachmentId = $attachmentId;
        $this->download = $download;
    }
}