<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** OAuth grant type, must be 'refresh_token' */
enum GrantTypeRefreshToken: string
{
    case RefreshToken = 'refresh_token';
}
