<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** OAuth grant type, must be 'authorization_code' */
enum GrantTypeAuthorizationCode: string
{
    case AuthorizationCode = 'authorization_code';
}
