<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class LineItem
{
    /**
     *
     * @var ?float $quantity
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantity')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $quantity = null;

    /**
     *
     * @var ?float $price
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('price')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $price = null;

    /**
     * Line item description in TipTap JSONContent format
     *
     * @var ?Name $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\Name|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Name $name = null;

    /**
     *
     * @var ?string $unit
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('unit')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $unit = null;

    /**
     *
     * @var ?float $vat
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('vat')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $vat = null;

    /**
     *
     * @var ?float $tax
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tax')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $tax = null;

    /**
     * @param  ?float  $quantity
     * @param  ?float  $price
     * @param  ?Name  $name
     * @param  ?string  $unit
     * @param  ?float  $vat
     * @param  ?float  $tax
     * @phpstan-pure
     */
    public function __construct(?float $quantity = null, ?float $price = null, ?Name $name = null, ?string $unit = null, ?float $vat = null, ?float $tax = null)
    {
        $this->quantity = $quantity;
        $this->price = $price;
        $this->name = $name;
        $this->unit = $unit;
        $this->vat = $vat;
        $this->tax = $tax;
    }
}