<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class ListTransactionsRequest
{
    /**
     *
     * @var ?float $pageSize
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=pageSize')]
    public ?float $pageSize = null;

    /**
     *
     * @var ?string $cursor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;

    /**
     * $sort
     *
     * @var ?array<string> $sort
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sort')]
    public ?array $sort = null;

    /**
     *
     * @var ?string $q
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=q')]
    public ?string $q = null;

    /**
     * $categories
     *
     * @var ?array<string> $categories
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=categories')]
    public ?array $categories = null;

    /**
     * $tags
     *
     * @var ?array<string> $tags
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tags')]
    public ?array $tags = null;

    /**
     *
     * @var ?string $start
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=start')]
    public ?string $start = null;

    /**
     *
     * @var ?string $end
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=end')]
    public ?string $end = null;

    /**
     * $accounts
     *
     * @var ?array<string> $accounts
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=accounts')]
    public ?array $accounts = null;

    /**
     * $assignees
     *
     * @var ?array<string> $assignees
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=assignees')]
    public ?array $assignees = null;

    /**
     * $statuses
     *
     * @var ?array<string> $statuses
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=statuses')]
    public ?array $statuses = null;

    /**
     * $recurring
     *
     * @var ?array<string> $recurring
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=recurring')]
    public ?array $recurring = null;

    /**
     * Filter transactions based on attachment presence. 'include' returns only transactions with attachments, 'exclude' returns only transactions without attachments
     *
     * @var ?Attachments $attachments
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=attachments')]
    public ?Attachments $attachments = null;

    /**
     * $amountRange
     *
     * @var ?array<?float> $amountRange
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=amountRange')]
    public ?array $amountRange = null;

    /**
     * $amount
     *
     * @var ?array<string> $amount
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=amount')]
    public ?array $amount = null;

    /**
     * Transaction type to filter by. 'income' for money received, 'expense' for money spent
     *
     * @var ?ListTransactionsType $type
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=type')]
    public ?ListTransactionsType $type = null;

    /**
     * @param  ?float  $pageSize
     * @param  ?string  $cursor
     * @param  ?array<string>  $sort
     * @param  ?string  $q
     * @param  ?array<string>  $categories
     * @param  ?array<string>  $tags
     * @param  ?string  $start
     * @param  ?string  $end
     * @param  ?array<string>  $accounts
     * @param  ?array<string>  $assignees
     * @param  ?array<string>  $statuses
     * @param  ?array<string>  $recurring
     * @param  ?Attachments  $attachments
     * @param  ?array<?float>  $amountRange
     * @param  ?array<string>  $amount
     * @param  ?ListTransactionsType  $type
     * @phpstan-pure
     */
    public function __construct(?float $pageSize = null, ?string $cursor = null, ?array $sort = null, ?string $q = null, ?array $categories = null, ?array $tags = null, ?string $start = null, ?string $end = null, ?array $accounts = null, ?array $assignees = null, ?array $statuses = null, ?array $recurring = null, ?Attachments $attachments = null, ?array $amountRange = null, ?array $amount = null, ?ListTransactionsType $type = null)
    {
        $this->pageSize = $pageSize;
        $this->cursor = $cursor;
        $this->sort = $sort;
        $this->q = $q;
        $this->categories = $categories;
        $this->tags = $tags;
        $this->start = $start;
        $this->end = $end;
        $this->accounts = $accounts;
        $this->assignees = $assignees;
        $this->statuses = $statuses;
        $this->recurring = $recurring;
        $this->attachments = $attachments;
        $this->amountRange = $amountRange;
        $this->amount = $amount;
        $this->type = $type;
    }
}