<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** Transaction type to filter by. 'income' for money received, 'expense' for money spent */
enum ListTransactionsType: string
{
    case Income = 'income';
    case Expense = 'expense';
}
