<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** ListTrackerEntriesResponseBody - List all tracker entries for the authenticated team. */
class ListTrackerEntriesResponseBody
{
    /**
     * Metadata about the tracker entries response including totals and date range
     *
     * @var ListTrackerEntriesMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\ListTrackerEntriesMeta')]
    public ListTrackerEntriesMeta $meta;

    /**
     * Tracker entries grouped by date, where each key is a date in YYYY-MM-DD format and the value is an array of tracker entries for that date
     *
     * @var array<string, array<Result>> $result
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('result')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, array<\Midday\Midday\Models\Operations\Result>>')]
    public array $result;

    /**
     * @param  ListTrackerEntriesMeta  $meta
     * @param  array<string, array<Result>>  $result
     * @phpstan-pure
     */
    public function __construct(ListTrackerEntriesMeta $meta, array $result)
    {
        $this->meta = $meta;
        $this->result = $result;
    }
}