<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** Current subscription plan of the team */
enum ListTeamsPlan: string
{
    case Trial = 'trial';
    case Starter = 'starter';
    case Pro = 'pro';
}
