<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** ListTeamMembersResponseBody - Team members */
class ListTeamMembersResponseBody
{
    /**
     * Array of team members with their roles and information
     *
     * @var array<ListTeamMembersData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Operations\ListTeamMembersData>')]
    public array $data;

    /**
     * @param  array<ListTeamMembersData>  $data
     * @phpstan-pure
     */
    public function __construct(array $data)
    {
        $this->data = $data;
    }
}