<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** ListInboxItemsMeta - Pagination metadata for the inbox list response. */
class ListInboxItemsMeta
{
    /**
     * Whether there is a previous page of results.
     *
     * @var bool $hasPreviousPage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasPreviousPage')]
    public bool $hasPreviousPage;

    /**
     * Whether there is a next page of results.
     *
     * @var bool $hasNextPage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasNextPage')]
    public bool $hasNextPage;

    /**
     * A cursor for pagination, representing the last item from the previous page.
     *
     * @var ?string $cursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cursor')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $cursor = null;

    /**
     * @param  bool  $hasPreviousPage
     * @param  bool  $hasNextPage
     * @param  ?string  $cursor
     * @phpstan-pure
     */
    public function __construct(bool $hasPreviousPage, bool $hasNextPage, ?string $cursor = null)
    {
        $this->hasPreviousPage = $hasPreviousPage;
        $this->hasNextPage = $hasNextPage;
        $this->cursor = $cursor;
    }
}