<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** ListDocumentsResponseBody - Response containing a list of documents and pagination metadata. */
class ListDocumentsResponseBody
{
    /**
     * Pagination metadata for the documents list.
     *
     * @var ListDocumentsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\ListDocumentsMeta')]
    public ListDocumentsMeta $meta;

    /**
     * Array of document objects.
     *
     * @var array<ListDocumentsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Operations\ListDocumentsData>')]
    public array $data;

    /**
     * @param  ListDocumentsMeta  $meta
     * @param  array<ListDocumentsData>  $data
     * @phpstan-pure
     */
    public function __construct(ListDocumentsMeta $meta, array $data)
    {
        $this->meta = $meta;
        $this->data = $data;
    }
}