<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class ListTrackerEntriesRequest
{
    /**
     *
     * @var string $from
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=from')]
    public string $from;

    /**
     *
     * @var string $to
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=to')]
    public string $to;

    /**
     *
     * @var ?string $projectId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=projectId')]
    public ?string $projectId = null;

    /**
     * @param  string  $from
     * @param  string  $to
     * @param  ?string  $projectId
     * @phpstan-pure
     */
    public function __construct(string $from, string $to, ?string $projectId = null)
    {
        $this->from = $from;
        $this->to = $to;
        $this->projectId = $projectId;
    }
}