<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** ListInboxItemsResponseBody - Retrieve a list of inbox items for the authenticated team. */
class ListInboxItemsResponseBody
{
    /**
     * Pagination metadata for the inbox list response.
     *
     * @var ListInboxItemsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\ListInboxItemsMeta')]
    public ListInboxItemsMeta $meta;

    /**
     * List of inbox items
     *
     * @var array<ListInboxItemsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Operations\ListInboxItemsData>')]
    public array $data;

    /**
     * @param  ListInboxItemsMeta  $meta
     * @param  array<ListInboxItemsData>  $data
     * @phpstan-pure
     */
    public function __construct(ListInboxItemsMeta $meta, array $data)
    {
        $this->meta = $meta;
        $this->data = $data;
    }
}