<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class ListTeamMembersData
{
    /**
     * Unique identifier of the user
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Role of the team member. 'owner' has full permissions, 'member' has limited permissions
     *
     * @var Role $role
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('role')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\Role')]
    public Role $role;

    /**
     * Full name of the team member
     *
     * @var string $fullName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fullName')]
    public string $fullName;

    /**
     * URL to the team member's avatar image
     *
     * @var ?string $avatarUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('avatarUrl')]
    public ?string $avatarUrl;

    /**
     * @param  string  $id
     * @param  Role  $role
     * @param  string  $fullName
     * @param  ?string  $avatarUrl
     * @phpstan-pure
     */
    public function __construct(string $id, Role $role, string $fullName, ?string $avatarUrl = null)
    {
        $this->id = $id;
        $this->role = $role;
        $this->fullName = $fullName;
        $this->avatarUrl = $avatarUrl;
    }
}