<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** ListTrackerEntriesMeta - Metadata about the tracker entries response including totals and date range */
class ListTrackerEntriesMeta
{
    /**
     * Total duration of all tracker entries in the response in seconds
     *
     * @var float $totalDuration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalDuration')]
    public float $totalDuration;

    /**
     * Total monetary amount for all tracker entries in the response
     *
     * @var float $totalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalAmount')]
    public float $totalAmount;

    /**
     * Start date of the queried range in YYYY-MM-DD format
     *
     * @var string $from
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('from')]
    public string $from;

    /**
     * End date of the queried range in YYYY-MM-DD format
     *
     * @var string $to
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('to')]
    public string $to;

    /**
     * @param  float  $totalDuration
     * @param  float  $totalAmount
     * @param  string  $from
     * @param  string  $to
     * @phpstan-pure
     */
    public function __construct(float $totalDuration, float $totalAmount, string $from, string $to)
    {
        $this->totalDuration = $totalDuration;
        $this->totalAmount = $totalAmount;
        $this->from = $from;
        $this->to = $to;
    }
}