<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class ListNotificationsRequest
{
    /**
     *
     * @var ?float $pageSize
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=pageSize')]
    public ?float $pageSize = null;

    /**
     * Filter by notification status. Can be a single status or array of statuses. unread = new notifications, read = viewed but not dismissed, archived = dismissed from view
     *
     * @var ListNotificationsStatusEnum1|array<ListNotificationsStatusEnum2>|null $status
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ListNotificationsStatusEnum1|array|null $status = null;

    /**
     *
     * @var ?string $cursor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;

    /**
     *
     * @var ?string $userId
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=userId')]
    public ?string $userId = null;

    /**
     *
     * @var ?int $priority
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=priority')]
    public ?int $priority = null;

    /**
     *
     * @var ?int $maxPriority
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=maxPriority')]
    public ?int $maxPriority = null;

    /**
     * @param  ?float  $pageSize
     * @param  ListNotificationsStatusEnum1|array<ListNotificationsStatusEnum2>|null  $status
     * @param  ?string  $cursor
     * @param  ?string  $userId
     * @param  ?int  $priority
     * @param  ?int  $maxPriority
     * @phpstan-pure
     */
    public function __construct(?float $pageSize = null, ListNotificationsStatusEnum1|array|null $status = null, ?string $cursor = null, ?string $userId = null, ?int $priority = null, ?int $maxPriority = null)
    {
        $this->pageSize = $pageSize;
        $this->status = $status;
        $this->cursor = $cursor;
        $this->userId = $userId;
        $this->priority = $priority;
        $this->maxPriority = $maxPriority;
    }
}