<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class ListInboxItemsRequest
{
    /**
     *
     * @var ?float $pageSize
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=pageSize')]
    public ?float $pageSize = null;

    /**
     *
     * @var ?string $cursor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;

    /**
     *
     * @var ?string $order
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=order')]
    public ?string $order = null;

    /**
     *
     * @var ?string $q
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=q')]
    public ?string $q = null;

    /**
     *
     * @var ?ListInboxItemsStatus $status
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=status')]
    public ?ListInboxItemsStatus $status = null;

    /**
     * @param  ?float  $pageSize
     * @param  ?string  $cursor
     * @param  ?string  $order
     * @param  ?string  $q
     * @param  ?ListInboxItemsStatus  $status
     * @phpstan-pure
     */
    public function __construct(?float $pageSize = null, ?string $cursor = null, ?string $order = null, ?string $q = null, ?ListInboxItemsStatus $status = null)
    {
        $this->pageSize = $pageSize;
        $this->cursor = $cursor;
        $this->order = $order;
        $this->q = $q;
        $this->status = $status;
    }
}