<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class ListDocumentsRequest
{
    /**
     *
     * @var ?float $pageSize
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=pageSize')]
    public ?float $pageSize = null;

    /**
     *
     * @var ?string $cursor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;

    /**
     * $sort
     *
     * @var ?array<string> $sort
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sort')]
    public ?array $sort = null;

    /**
     *
     * @var ?string $q
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=q')]
    public ?string $q = null;

    /**
     * $tags
     *
     * @var ?array<string> $tags
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=tags')]
    public ?array $tags = null;

    /**
     * @param  ?float  $pageSize
     * @param  ?string  $cursor
     * @param  ?array<string>  $sort
     * @param  ?string  $q
     * @param  ?array<string>  $tags
     * @phpstan-pure
     */
    public function __construct(?float $pageSize = null, ?string $cursor = null, ?array $sort = null, ?string $q = null, ?array $tags = null)
    {
        $this->pageSize = $pageSize;
        $this->cursor = $cursor;
        $this->sort = $sort;
        $this->q = $q;
        $this->tags = $tags;
    }
}