<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** ListCustomersResponseBody - Retrieve a list of customers for the authenticated team. */
class ListCustomersResponseBody
{
    /**
     * Pagination metadata for the customers response
     *
     * @var ListCustomersMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\ListCustomersMeta')]
    public ListCustomersMeta $meta;

    /**
     * Array of customers matching the query criteria
     *
     * @var array<ListCustomersData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Operations\ListCustomersData>')]
    public array $data;

    /**
     * @param  ListCustomersMeta  $meta
     * @param  array<ListCustomersData>  $data
     * @phpstan-pure
     */
    public function __construct(ListCustomersMeta $meta, array $data)
    {
        $this->meta = $meta;
        $this->data = $data;
    }
}