<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class ListTeamsData
{
    /**
     * Unique identifier of the team
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Name of the team or organization
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Current subscription plan of the team
     *
     * @var ListTeamsPlan $plan
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('plan')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\ListTeamsPlan')]
    public ListTeamsPlan $plan;

    /**
     * URL to the team's logo image
     *
     * @var ?string $logoUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logoUrl')]
    public ?string $logoUrl;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  ListTeamsPlan  $plan
     * @param  ?string  $logoUrl
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, ListTeamsPlan $plan, ?string $logoUrl = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->plan = $plan;
        $this->logoUrl = $logoUrl;
    }
}