<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;



enum ListInboxItemsStatus: string
{
    case Done = 'done';
    case Pending = 'pending';
}
