<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** ListInvoicesMeta - Pagination metadata */
class ListInvoicesMeta
{
    /**
     * Indicates if there is a previous page of results
     *
     * @var bool $hasPreviousPage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasPreviousPage')]
    public bool $hasPreviousPage;

    /**
     * Indicates if there is a next page of results
     *
     * @var bool $hasNextPage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasNextPage')]
    public bool $hasNextPage;

    /**
     * Cursor for pagination; null if there is no next page
     *
     * @var ?string $cursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cursor')]
    public ?string $cursor;

    /**
     * @param  bool  $hasPreviousPage
     * @param  bool  $hasNextPage
     * @param  ?string  $cursor
     * @phpstan-pure
     */
    public function __construct(bool $hasPreviousPage, bool $hasNextPage, ?string $cursor = null)
    {
        $this->hasPreviousPage = $hasPreviousPage;
        $this->hasNextPage = $hasNextPage;
        $this->cursor = $cursor;
    }
}