<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class ListInvoicesRequest
{
    /**
     *
     * @var ?float $pageSize
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=pageSize')]
    public ?float $pageSize = null;

    /**
     *
     * @var ?string $cursor
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=cursor')]
    public ?string $cursor = null;

    /**
     * $sort
     *
     * @var ?array<string> $sort
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=sort')]
    public ?array $sort = null;

    /**
     *
     * @var ?string $q
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=q')]
    public ?string $q = null;

    /**
     *
     * @var ?string $start
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=start')]
    public ?string $start = null;

    /**
     *
     * @var ?string $end
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=end')]
    public ?string $end = null;

    /**
     * $statuses
     *
     * @var ?array<string> $statuses
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=statuses')]
    public ?array $statuses = null;

    /**
     * $customers
     *
     * @var ?array<string> $customers
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=customers')]
    public ?array $customers = null;

    /**
     * @param  ?float  $pageSize
     * @param  ?string  $cursor
     * @param  ?array<string>  $sort
     * @param  ?string  $q
     * @param  ?string  $start
     * @param  ?string  $end
     * @param  ?array<string>  $statuses
     * @param  ?array<string>  $customers
     * @phpstan-pure
     */
    public function __construct(?float $pageSize = null, ?string $cursor = null, ?array $sort = null, ?string $q = null, ?string $start = null, ?string $end = null, ?array $statuses = null, ?array $customers = null)
    {
        $this->pageSize = $pageSize;
        $this->cursor = $cursor;
        $this->sort = $sort;
        $this->q = $q;
        $this->start = $start;
        $this->end = $end;
        $this->statuses = $statuses;
        $this->customers = $customers;
    }
}