<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class ListBankAccountsRequest
{
    /**
     *
     * @var ?bool $enabled
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=enabled')]
    public ?bool $enabled = null;

    /**
     *
     * @var ?bool $manual
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=manual')]
    public ?bool $manual = null;

    /**
     * @param  ?bool  $enabled
     * @param  ?bool  $manual
     * @phpstan-pure
     */
    public function __construct(?bool $enabled = null, ?bool $manual = null)
    {
        $this->enabled = $enabled;
        $this->manual = $manual;
    }
}