<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** ListBankAccountsResponseBody - Response containing a list of bank accounts. */
class ListBankAccountsResponseBody
{
    /**
     * Array of bank account objects.
     *
     * @var array<ListBankAccountsData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Operations\ListBankAccountsData>')]
    public array $data;

    /**
     * @param  array<ListBankAccountsData>  $data
     * @phpstan-pure
     */
    public function __construct(array $data)
    {
        $this->data = $data;
    }
}