<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** ListInvoicesResponseBody - Response containing a list of invoices and pagination metadata */
class ListInvoicesResponseBody
{
    /**
     * Pagination metadata
     *
     * @var ListInvoicesMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\ListInvoicesMeta')]
    public ListInvoicesMeta $meta;

    /**
     * Array of invoice objects
     *
     * @var array<ListInvoicesData> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Operations\ListInvoicesData>')]
    public array $data;

    /**
     * @param  ListInvoicesMeta  $meta
     * @param  array<ListInvoicesData>  $data
     * @phpstan-pure
     */
    public function __construct(ListInvoicesMeta $meta, array $data)
    {
        $this->meta = $meta;
        $this->data = $data;
    }
}