<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** Name - Line item description in TipTap JSONContent format */
class Name
{

    public function __construct()
    {
    }
}