<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** NoteDetails - Additional notes for the invoice in TipTap JSONContent format */
class NoteDetails
{

    public function __construct()
    {
    }
}