<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** PostOAuthTokenResponseBody - Token exchange successful */
class PostOAuthTokenResponseBody
{
    /**
     * Access token for API requests
     *
     * @var string $accessToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('access_token')]
    public string $accessToken;

    /**
     * Token type, always 'Bearer'
     *
     * @var TokenType $tokenType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('token_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\TokenType')]
    public TokenType $tokenType;

    /**
     * Token expiration time in seconds
     *
     * @var float $expiresIn
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('expires_in')]
    public float $expiresIn;

    /**
     * Refresh token for obtaining new access tokens
     *
     * @var string $refreshToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refresh_token')]
    public string $refreshToken;

    /**
     * Space-separated list of granted scopes
     *
     * @var string $scope
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scope')]
    public string $scope;

    /**
     * @param  string  $accessToken
     * @param  TokenType  $tokenType
     * @param  float  $expiresIn
     * @param  string  $refreshToken
     * @param  string  $scope
     * @phpstan-pure
     */
    public function __construct(string $accessToken, TokenType $tokenType, float $expiresIn, string $refreshToken, string $scope)
    {
        $this->accessToken = $accessToken;
        $this->tokenType = $tokenType;
        $this->expiresIn = $expiresIn;
        $this->refreshToken = $refreshToken;
        $this->scope = $scope;
    }
}