<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** PostOAuthAuthorizationResponseBody - Authorization decision processed, returns redirect URL */
class PostOAuthAuthorizationResponseBody
{
    /**
     *
     * @var string $redirectUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('redirect_url')]
    public string $redirectUrl;

    /**
     * @param  string  $redirectUrl
     * @phpstan-pure
     */
    public function __construct(string $redirectUrl)
    {
        $this->redirectUrl = $redirectUrl;
    }
}