<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class PostOAuthAuthorizationRequest
{
    /**
     * Client ID of the OAuth application
     *
     * @var string $clientId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('client_id')]
    public string $clientId;

    /**
     * User's authorization decision
     *
     * @var Decision $decision
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('decision')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\Decision')]
    public Decision $decision;

    /**
     * Scopes the user has approved
     *
     * @var array<Scope> $scopes
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scopes')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Operations\Scope>')]
    public array $scopes;

    /**
     * Redirect URI for OAuth callback
     *
     * @var string $redirectUri
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('redirect_uri')]
    public string $redirectUri;

    /**
     * State parameter for CSRF protection (min 32 chars, alphanumeric + _.-)
     *
     * @var string $state
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('state')]
    public string $state;

    /**
     * Team ID to authorize the application for
     *
     * @var string $teamId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('teamId')]
    public string $teamId;

    /**
     * Code challenge for PKCE (S256 method assumed)
     *
     * @var ?string $codeChallenge
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('code_challenge')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $codeChallenge = null;

    /**
     * @param  string  $clientId
     * @param  Decision  $decision
     * @param  array<Scope>  $scopes
     * @param  string  $redirectUri
     * @param  string  $state
     * @param  string  $teamId
     * @param  ?string  $codeChallenge
     * @phpstan-pure
     */
    public function __construct(string $clientId, Decision $decision, array $scopes, string $redirectUri, string $state, string $teamId, ?string $codeChallenge = null)
    {
        $this->clientId = $clientId;
        $this->decision = $decision;
        $this->scopes = $scopes;
        $this->redirectUri = $redirectUri;
        $this->state = $state;
        $this->teamId = $teamId;
        $this->codeChallenge = $codeChallenge;
    }
}