<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** Project - Project information associated with this tracker entry */
class Project
{
    /**
     * Unique identifier of the project
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Date and time when the project was created in ISO 8601 format
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     * Default hourly rate for the project
     *
     * @var float $rate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rate')]
    public float $rate;

    /**
     * Currency code for the project rate in ISO 4217 format
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * Current status of the project
     *
     * @var string $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    public string $status;

    /**
     * Description of the project
     *
     * @var string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public string $description;

    /**
     * Name of the project
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Whether the project is billable to the customer
     *
     * @var bool $billable
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billable')]
    public bool $billable;

    /**
     * Estimated total hours for the project
     *
     * @var float $estimate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('estimate')]
    public float $estimate;

    /**
     * Customer information associated with the project
     *
     * @var ListTrackerEntriesCustomer $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\ListTrackerEntriesCustomer')]
    public ListTrackerEntriesCustomer $customer;

    /**
     * @param  string  $id
     * @param  string  $createdAt
     * @param  float  $rate
     * @param  string  $currency
     * @param  string  $status
     * @param  string  $description
     * @param  string  $name
     * @param  bool  $billable
     * @param  float  $estimate
     * @param  ListTrackerEntriesCustomer  $customer
     * @phpstan-pure
     */
    public function __construct(string $id, string $createdAt, float $rate, string $currency, string $status, string $description, string $name, bool $billable, float $estimate, ListTrackerEntriesCustomer $customer)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->rate = $rate;
        $this->currency = $currency;
        $this->status = $status;
        $this->description = $description;
        $this->name = $name;
        $this->billable = $billable;
        $this->estimate = $estimate;
        $this->customer = $customer;
    }
}