<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class RefreshToken
{
    /**
     * OAuth grant type, must be 'refresh_token'
     *
     * @var GrantTypeRefreshToken $grantType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('grant_type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\GrantTypeRefreshToken')]
    public GrantTypeRefreshToken $grantType;

    /**
     * Refresh token received from token endpoint
     *
     * @var string $refreshToken
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('refresh_token')]
    public string $refreshToken;

    /**
     * Client ID of the OAuth application
     *
     * @var string $clientId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('client_id')]
    public string $clientId;

    /**
     * Client secret of the OAuth application (required for confidential clients)
     *
     * @var ?string $clientSecret
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('client_secret')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $clientSecret = null;

    /**
     * Space-separated list of requested scopes (optional)
     *
     * @var ?string $scope
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('scope')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $scope = null;

    /**
     * @param  GrantTypeRefreshToken  $grantType
     * @param  string  $refreshToken
     * @param  string  $clientId
     * @param  ?string  $clientSecret
     * @param  ?string  $scope
     * @phpstan-pure
     */
    public function __construct(GrantTypeRefreshToken $grantType, string $refreshToken, string $clientId, ?string $clientSecret = null, ?string $scope = null)
    {
        $this->grantType = $grantType;
        $this->refreshToken = $refreshToken;
        $this->clientId = $clientId;
        $this->clientSecret = $clientSecret;
        $this->scope = $scope;
    }
}