<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** OAuth response type, must be 'code' */
enum ResponseType: string
{
    case Code = 'code';
}
