<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


enum Scope: string
{
    case BankAccountsRead = 'bank-accounts.read';
    case BankAccountsWrite = 'bank-accounts.write';
    case CustomersRead = 'customers.read';
    case CustomersWrite = 'customers.write';
    case DocumentsRead = 'documents.read';
    case DocumentsWrite = 'documents.write';
    case InboxRead = 'inbox.read';
    case InboxWrite = 'inbox.write';
    case InvoicesRead = 'invoices.read';
    case InvoicesWrite = 'invoices.write';
    case ReportsRead = 'reports.read';
    case SearchRead = 'search.read';
    case TagsRead = 'tags.read';
    case TagsWrite = 'tags.write';
    case TeamsRead = 'teams.read';
    case TeamsWrite = 'teams.write';
    case TrackerEntriesRead = 'tracker-entries.read';
    case TrackerEntriesWrite = 'tracker-entries.write';
    case TrackerProjectsRead = 'tracker-projects.read';
    case TrackerProjectsWrite = 'tracker-projects.write';
    case TransactionsRead = 'transactions.read';
    case TransactionsWrite = 'transactions.write';
    case UsersRead = 'users.read';
    case UsersWrite = 'users.write';
    case NotificationsRead = 'notifications.read';
    case NotificationsWrite = 'notifications.write';
    case ApisAll = 'apis.all';
    case ApisRead = 'apis.read';
}
