<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class SearchRequest
{
    /**
     *
     * @var ?string $searchTerm
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=searchTerm')]
    public ?string $searchTerm = null;

    /**
     *
     * @var ?string $language
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=language')]
    public ?string $language = null;

    /**
     *
     * @var ?float $limit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=limit')]
    public ?float $limit = null;

    /**
     *
     * @var ?float $itemsPerTableLimit
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=itemsPerTableLimit')]
    public ?float $itemsPerTableLimit = null;

    /**
     *
     * @var ?float $relevanceThreshold
     */
    #[SpeakeasyMetadata('queryParam:style=form,explode=true,name=relevanceThreshold')]
    public ?float $relevanceThreshold = null;

    /**
     * @param  ?string  $searchTerm
     * @param  ?string  $language
     * @param  ?float  $limit
     * @param  ?float  $itemsPerTableLimit
     * @param  ?float  $relevanceThreshold
     * @phpstan-pure
     */
    public function __construct(?string $searchTerm = null, ?string $language = null, ?float $limit = 30, ?float $itemsPerTableLimit = 5, ?float $relevanceThreshold = 0.01)
    {
        $this->searchTerm = $searchTerm;
        $this->language = $language;
        $this->limit = $limit;
        $this->itemsPerTableLimit = $itemsPerTableLimit;
        $this->relevanceThreshold = $relevanceThreshold;
    }
}