<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class SearchResponseBody
{
    /**
     * Unique identifier for the search result item.
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Type of the entity returned (e.g., invoice, customer, transaction).
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * Relevance score for the search result.
     *
     * @var float $relevance
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('relevance')]
    public float $relevance;

    /**
     * ISO 8601 timestamp when the entity was created.
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('created_at')]
    public string $createdAt;

    /**
     * Additional data for the search result, structure depends on the type.
     *
     * @var mixed $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('mixed')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public mixed $data = null;

    /**
     * @param  string  $id
     * @param  string  $type
     * @param  float  $relevance
     * @param  string  $createdAt
     * @param  mixed  $data
     * @phpstan-pure
     */
    public function __construct(string $id, string $type, float $relevance, string $createdAt, mixed $data = null)
    {
        $this->id = $id;
        $this->type = $type;
        $this->relevance = $relevance;
        $this->createdAt = $createdAt;
        $this->data = $data;
    }
}