<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


enum Size: string
{
    case A4 = 'a4';
    case Letter = 'letter';
}
