<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** StartTimerResponseBody - Timer started successfully. */
class StartTimerResponseBody
{
    /**
     *
     * @var StartTimerData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\StartTimerData')]
    public StartTimerData $data;

    /**
     * @param  StartTimerData  $data
     * @phpstan-pure
     */
    public function __construct(StartTimerData $data)
    {
        $this->data = $data;
    }
}