<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** StopTimerResponseBody - Timer stopped successfully. */
class StopTimerResponseBody
{
    /**
     *
     * @var StopTimerData $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\StopTimerData')]
    public StopTimerData $data;

    /**
     * @param  StopTimerData  $data
     * @phpstan-pure
     */
    public function __construct(StopTimerData $data)
    {
        $this->data = $data;
    }
}