<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** StopTimerProject - Project information associated with this tracker entry */
class StopTimerProject
{
    /**
     * Unique identifier of the project
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Date and time when the project was created in ISO 8601 format
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     * Current status of the project
     *
     * @var string $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    public string $status;

    /**
     * Name of the project
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Default hourly rate for the project
     *
     * @var ?float $rate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rate')]
    public ?float $rate;

    /**
     * Currency code for the project rate in ISO 4217 format
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public ?string $currency;

    /**
     * Description of the project
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public ?string $description;

    /**
     * Whether the project is billable to the customer
     *
     * @var ?bool $billable
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billable')]
    public ?bool $billable;

    /**
     * Estimated total hours for the project
     *
     * @var ?float $estimate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('estimate')]
    public ?float $estimate;

    /**
     * Customer information associated with the project
     *
     * @var ?StopTimerCustomer $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\StopTimerCustomer|null')]
    public ?StopTimerCustomer $customer;

    /**
     * @param  string  $id
     * @param  string  $createdAt
     * @param  string  $status
     * @param  string  $name
     * @param  ?float  $rate
     * @param  ?string  $currency
     * @param  ?string  $description
     * @param  ?bool  $billable
     * @param  ?float  $estimate
     * @param  ?StopTimerCustomer  $customer
     * @phpstan-pure
     */
    public function __construct(string $id, string $createdAt, string $status, string $name, ?float $rate = null, ?string $currency = null, ?string $description = null, ?bool $billable = null, ?float $estimate = null, ?StopTimerCustomer $customer = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->status = $status;
        $this->name = $name;
        $this->rate = $rate;
        $this->currency = $currency;
        $this->description = $description;
        $this->billable = $billable;
        $this->estimate = $estimate;
        $this->customer = $customer;
    }
}