<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** StopTimerUser - User information for the person who created this tracker entry */
class StopTimerUser
{
    /**
     * Unique identifier of the user
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Full name of the user
     *
     * @var string $fullName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fullName')]
    public string $fullName;

    /**
     * URL to the user's avatar image
     *
     * @var string $avatarUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('avatarUrl')]
    public string $avatarUrl;

    /**
     * @param  string  $id
     * @param  string  $fullName
     * @param  string  $avatarUrl
     * @phpstan-pure
     */
    public function __construct(string $id, string $fullName, string $avatarUrl)
    {
        $this->id = $id;
        $this->fullName = $fullName;
        $this->avatarUrl = $avatarUrl;
    }
}