<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** Template - Invoice template details */
class Template
{
    /**
     *
     * @var ?string $customerLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customerLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerLabel = null;

    /**
     *
     * @var ?string $title
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('title')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $title = null;

    /**
     *
     * @var ?string $fromLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fromLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $fromLabel = null;

    /**
     *
     * @var ?string $invoiceNoLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('invoiceNoLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $invoiceNoLabel = null;

    /**
     *
     * @var ?string $issueDateLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('issueDateLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $issueDateLabel = null;

    /**
     *
     * @var ?string $dueDateLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dueDateLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $dueDateLabel = null;

    /**
     *
     * @var ?string $descriptionLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('descriptionLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $descriptionLabel = null;

    /**
     *
     * @var ?string $priceLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('priceLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $priceLabel = null;

    /**
     *
     * @var ?string $quantityLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('quantityLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $quantityLabel = null;

    /**
     *
     * @var ?string $totalLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $totalLabel = null;

    /**
     *
     * @var ?string $totalSummaryLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalSummaryLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $totalSummaryLabel = null;

    /**
     *
     * @var ?string $vatLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('vatLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $vatLabel = null;

    /**
     *
     * @var ?string $subtotalLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('subtotalLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $subtotalLabel = null;

    /**
     *
     * @var ?string $taxLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('taxLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $taxLabel = null;

    /**
     *
     * @var ?string $discountLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('discountLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $discountLabel = null;

    /**
     *
     * @var ?string $timezone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timezone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $timezone = null;

    /**
     *
     * @var ?string $paymentLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $paymentLabel = null;

    /**
     *
     * @var ?string $noteLabel
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('noteLabel')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $noteLabel = null;

    /**
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     *
     * @var ?string $dateFormat
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dateFormat')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $dateFormat = null;

    /**
     *
     * @var ?bool $includeVat
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('includeVat')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $includeVat = null;

    /**
     *
     * @var ?bool $includeTax
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('includeTax')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $includeTax = null;

    /**
     *
     * @var ?bool $includeDiscount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('includeDiscount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $includeDiscount = null;

    /**
     *
     * @var ?bool $includeDecimals
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('includeDecimals')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $includeDecimals = null;

    /**
     *
     * @var ?bool $includePdf
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('includePdf')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $includePdf = null;

    /**
     *
     * @var ?bool $sendCopy
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('sendCopy')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $sendCopy = null;

    /**
     *
     * @var ?bool $includeUnits
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('includeUnits')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $includeUnits = null;

    /**
     *
     * @var ?bool $includeQr
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('includeQr')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $includeQr = null;

    /**
     *
     * @var ?float $taxRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('taxRate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $taxRate = null;

    /**
     *
     * @var ?float $vatRate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('vatRate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $vatRate = null;

    /**
     *
     * @var ?Size $size
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('size')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\Size|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?Size $size = null;

    /**
     *
     * @var ?TemplateDeliveryType $deliveryType
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('deliveryType')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\TemplateDeliveryType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TemplateDeliveryType $deliveryType = null;

    /**
     *
     * @var ?string $locale
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('locale')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $locale = null;

    /**
     * Payment details in TipTap JSONContent format
     *
     * @var ?TemplatePaymentDetails $paymentDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paymentDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\TemplatePaymentDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TemplatePaymentDetails $paymentDetails = null;

    /**
     * Sender details in TipTap JSONContent format
     *
     * @var ?TemplateFromDetails $fromDetails
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fromDetails')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\TemplateFromDetails|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?TemplateFromDetails $fromDetails = null;

    /**
     *
     * @var ?string $logoUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logoUrl')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $logoUrl = null;

    /**
     * @param  ?string  $customerLabel
     * @param  ?string  $title
     * @param  ?string  $fromLabel
     * @param  ?string  $invoiceNoLabel
     * @param  ?string  $issueDateLabel
     * @param  ?string  $dueDateLabel
     * @param  ?string  $descriptionLabel
     * @param  ?string  $priceLabel
     * @param  ?string  $quantityLabel
     * @param  ?string  $totalLabel
     * @param  ?string  $totalSummaryLabel
     * @param  ?string  $vatLabel
     * @param  ?string  $subtotalLabel
     * @param  ?string  $taxLabel
     * @param  ?string  $discountLabel
     * @param  ?string  $timezone
     * @param  ?string  $paymentLabel
     * @param  ?string  $noteLabel
     * @param  ?string  $currency
     * @param  ?string  $dateFormat
     * @param  ?bool  $includeVat
     * @param  ?bool  $includeTax
     * @param  ?bool  $includeDiscount
     * @param  ?bool  $includeDecimals
     * @param  ?bool  $includePdf
     * @param  ?bool  $sendCopy
     * @param  ?bool  $includeUnits
     * @param  ?bool  $includeQr
     * @param  ?float  $taxRate
     * @param  ?float  $vatRate
     * @param  ?Size  $size
     * @param  ?TemplateDeliveryType  $deliveryType
     * @param  ?string  $locale
     * @param  ?TemplatePaymentDetails  $paymentDetails
     * @param  ?TemplateFromDetails  $fromDetails
     * @param  ?string  $logoUrl
     * @phpstan-pure
     */
    public function __construct(?string $customerLabel = null, ?string $title = null, ?string $fromLabel = null, ?string $invoiceNoLabel = null, ?string $issueDateLabel = null, ?string $dueDateLabel = null, ?string $descriptionLabel = null, ?string $priceLabel = null, ?string $quantityLabel = null, ?string $totalLabel = null, ?string $totalSummaryLabel = null, ?string $vatLabel = null, ?string $subtotalLabel = null, ?string $taxLabel = null, ?string $discountLabel = null, ?string $timezone = null, ?string $paymentLabel = null, ?string $noteLabel = null, ?string $currency = null, ?string $dateFormat = null, ?bool $includeVat = null, ?bool $includeTax = null, ?bool $includeDiscount = null, ?bool $includeDecimals = null, ?bool $includePdf = null, ?bool $sendCopy = null, ?bool $includeUnits = null, ?bool $includeQr = null, ?float $taxRate = null, ?float $vatRate = null, ?Size $size = null, ?TemplateDeliveryType $deliveryType = null, ?string $locale = null, ?TemplatePaymentDetails $paymentDetails = null, ?TemplateFromDetails $fromDetails = null, ?string $logoUrl = null)
    {
        $this->customerLabel = $customerLabel;
        $this->title = $title;
        $this->fromLabel = $fromLabel;
        $this->invoiceNoLabel = $invoiceNoLabel;
        $this->issueDateLabel = $issueDateLabel;
        $this->dueDateLabel = $dueDateLabel;
        $this->descriptionLabel = $descriptionLabel;
        $this->priceLabel = $priceLabel;
        $this->quantityLabel = $quantityLabel;
        $this->totalLabel = $totalLabel;
        $this->totalSummaryLabel = $totalSummaryLabel;
        $this->vatLabel = $vatLabel;
        $this->subtotalLabel = $subtotalLabel;
        $this->taxLabel = $taxLabel;
        $this->discountLabel = $discountLabel;
        $this->timezone = $timezone;
        $this->paymentLabel = $paymentLabel;
        $this->noteLabel = $noteLabel;
        $this->currency = $currency;
        $this->dateFormat = $dateFormat;
        $this->includeVat = $includeVat;
        $this->includeTax = $includeTax;
        $this->includeDiscount = $includeDiscount;
        $this->includeDecimals = $includeDecimals;
        $this->includePdf = $includePdf;
        $this->sendCopy = $sendCopy;
        $this->includeUnits = $includeUnits;
        $this->includeQr = $includeQr;
        $this->taxRate = $taxRate;
        $this->vatRate = $vatRate;
        $this->size = $size;
        $this->deliveryType = $deliveryType;
        $this->locale = $locale;
        $this->paymentDetails = $paymentDetails;
        $this->fromDetails = $fromDetails;
        $this->logoUrl = $logoUrl;
    }
}