<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


enum TemplateDeliveryType: string
{
    case Create = 'create';
    case CreateAndSend = 'create_and_send';
    case Scheduled = 'scheduled';
}
