<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** TemplatePaymentDetails - Payment details in TipTap JSONContent format */
class TemplatePaymentDetails
{

    public function __construct()
    {
    }
}