<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** Token type, always 'Bearer' */
enum TokenType: string
{
    case Bearer = 'Bearer';
}
