<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** TopBlock - Custom content block to display at the top of the invoice in TipTap JSONContent format */
class TopBlock
{

    public function __construct()
    {
    }
}