<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class UpdateNotificationStatusRequestBody
{
    /**
     * The new status for the notification
     *
     * @var UpdateNotificationStatusStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\UpdateNotificationStatusStatus')]
    public UpdateNotificationStatusStatus $status;

    /**
     * @param  UpdateNotificationStatusStatus  $status
     * @phpstan-pure
     */
    public function __construct(UpdateNotificationStatusStatus $status)
    {
        $this->status = $status;
    }
}