<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


enum UpdateInboxItemStatus: string
{
    case New = 'new';
    case Archived = 'archived';
    case Processing = 'processing';
    case Done = 'done';
    case Pending = 'pending';
}
