<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Models\Components;
/** UpdateTransactionsResponseBody - Transactions updated */
class UpdateTransactionsResponseBody
{
    /**
     * Pagination metadata for the transactions response
     *
     * @var UpdateTransactionsMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\UpdateTransactionsMeta')]
    public UpdateTransactionsMeta $meta;

    /**
     * Array of transactions matching the query criteria
     *
     * @var array<Components\TransactionResponse> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Components\TransactionResponse>')]
    public array $data;

    /**
     * @param  UpdateTransactionsMeta  $meta
     * @param  array<Components\TransactionResponse>  $data
     * @phpstan-pure
     */
    public function __construct(UpdateTransactionsMeta $meta, array $data)
    {
        $this->meta = $meta;
        $this->data = $data;
    }
}