<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class UpdateTransactionRequestBody
{
    /**
     * Whether the transaction is internal.
     *
     * @var ?bool $internal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('internal')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $internal = null;

    /**
     * Whether the transaction is recurring.
     *
     * @var ?bool $recurring
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurring')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $recurring = null;

    /**
     * Category slug for the transaction.
     *
     * @var ?string $categorySlug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('categorySlug')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $categorySlug = null;

    /**
     * Status of the transaction.
     *
     * @var ?UpdateTransactionStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\UpdateTransactionStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateTransactionStatus $status = null;

    /**
     * Recurring frequency of the transaction.
     *
     * @var ?UpdateTransactionFrequency $frequency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('frequency')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\UpdateTransactionFrequency|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateTransactionFrequency $frequency = null;

    /**
     * Note for the transaction.
     *
     * @var ?string $note
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('note')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $note = null;

    /**
     * Assigned user ID for the transaction.
     *
     * @var ?string $assignedId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('assignedId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $assignedId = null;

    /**
     * @param  ?bool  $internal
     * @param  ?bool  $recurring
     * @param  ?string  $categorySlug
     * @param  ?UpdateTransactionStatus  $status
     * @param  ?UpdateTransactionFrequency  $frequency
     * @param  ?string  $note
     * @param  ?string  $assignedId
     * @phpstan-pure
     */
    public function __construct(?bool $internal = null, ?bool $recurring = null, ?string $categorySlug = null, ?UpdateTransactionStatus $status = null, ?UpdateTransactionFrequency $frequency = null, ?string $note = null, ?string $assignedId = null)
    {
        $this->internal = $internal;
        $this->recurring = $recurring;
        $this->categorySlug = $categorySlug;
        $this->status = $status;
        $this->frequency = $frequency;
        $this->note = $note;
        $this->assignedId = $assignedId;
    }
}