<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** Type of the bank account. */
enum UpdateBankAccountType: string
{
    case Depository = 'depository';
    case Credit = 'credit';
    case OtherAsset = 'other_asset';
    case Loan = 'loan';
    case OtherLiability = 'other_liability';
}
