<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** UpdateCurrentUserResponseBody - The updated user */
class UpdateCurrentUserResponseBody
{
    /**
     * Unique identifier of the user
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Full name of the user
     *
     * @var string $fullName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fullName')]
    public string $fullName;

    /**
     * Email address of the user
     *
     * @var string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    public string $email;

    /**
     * URL to the user's avatar image
     *
     * @var ?string $avatarUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('avatarUrl')]
    public ?string $avatarUrl;

    /**
     * User's preferred locale for internationalization (language and region)
     *
     * @var ?string $locale
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('locale')]
    public ?string $locale;

    /**
     * Whether the user's calendar week starts on Monday (true) or Sunday (false)
     *
     * @var ?bool $weekStartsOnMonday
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('weekStartsOnMonday')]
    public ?bool $weekStartsOnMonday;

    /**
     * User's timezone identifier in IANA Time Zone Database format
     *
     * @var ?string $timezone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timezone')]
    public ?string $timezone;

    /**
     * User's preferred time format: 12 for 12-hour format, 24 for 24-hour format
     *
     * @var ?float $timeFormat
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timeFormat')]
    public ?float $timeFormat;

    /**
     * User's preferred date format. Available options: 'dd/MM/yyyy', 'MM/dd/yyyy', 'yyyy-MM-dd', 'dd.MM.yyyy'
     *
     * @var ?UpdateCurrentUserDateFormatResponse $dateFormat
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dateFormat')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\UpdateCurrentUserDateFormatResponse|null')]
    public ?UpdateCurrentUserDateFormatResponse $dateFormat;

    /**
     * Team information that the user belongs to
     *
     * @var ?UpdateCurrentUserTeam $team
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('team')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\UpdateCurrentUserTeam|null')]
    public ?UpdateCurrentUserTeam $team;

    /**
     * @param  string  $id
     * @param  string  $fullName
     * @param  string  $email
     * @param  ?string  $avatarUrl
     * @param  ?string  $locale
     * @param  ?bool  $weekStartsOnMonday
     * @param  ?string  $timezone
     * @param  ?float  $timeFormat
     * @param  ?UpdateCurrentUserDateFormatResponse  $dateFormat
     * @param  ?UpdateCurrentUserTeam  $team
     * @phpstan-pure
     */
    public function __construct(string $id, string $fullName, string $email, ?string $avatarUrl = null, ?string $locale = null, ?bool $weekStartsOnMonday = null, ?string $timezone = null, ?float $timeFormat = null, ?UpdateCurrentUserDateFormatResponse $dateFormat = null, ?UpdateCurrentUserTeam $team = null)
    {
        $this->id = $id;
        $this->fullName = $fullName;
        $this->email = $email;
        $this->avatarUrl = $avatarUrl;
        $this->locale = $locale;
        $this->weekStartsOnMonday = $weekStartsOnMonday;
        $this->timezone = $timezone;
        $this->timeFormat = $timeFormat;
        $this->dateFormat = $dateFormat;
        $this->team = $team;
    }
}