<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** UpdateBankAccountRequestBody - Schema for updating a bank account. */
class UpdateBankAccountRequestBody
{
    /**
     * The unique identifier of the bank account.
     *
     * @var ?string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $id = null;

    /**
     * The name of the bank account.
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * Whether the bank account is enabled.
     *
     * @var ?bool $enabled
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('enabled')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $enabled = null;

    /**
     * Current balance of the bank account.
     *
     * @var ?float $balance
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('balance')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $balance = null;

    /**
     * The currency code for the bank account (ISO 4217).
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     * Type of the bank account.
     *
     * @var ?UpdateBankAccountType $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\UpdateBankAccountType|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateBankAccountType $type = null;

    /**
     * @param  ?string  $id
     * @param  ?string  $name
     * @param  ?bool  $enabled
     * @param  ?float  $balance
     * @param  ?string  $currency
     * @param  ?UpdateBankAccountType  $type
     * @phpstan-pure
     */
    public function __construct(?string $id = null, ?string $name = null, ?bool $enabled = null, ?float $balance = null, ?string $currency = null, ?UpdateBankAccountType $type = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->enabled = $enabled;
        $this->balance = $balance;
        $this->currency = $currency;
        $this->type = $type;
    }
}