<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class UpdateInboxItemRequestBody
{
    /**
     *
     * @var ?UpdateInboxItemStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\UpdateInboxItemStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateInboxItemStatus $status = null;

    /**
     *
     * @var ?string $displayName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('displayName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $displayName = null;

    /**
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     *
     * @var ?float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $amount = null;

    /**
     * @param  ?UpdateInboxItemStatus  $status
     * @param  ?string  $displayName
     * @param  ?string  $currency
     * @param  ?float  $amount
     * @phpstan-pure
     */
    public function __construct(?UpdateInboxItemStatus $status = null, ?string $displayName = null, ?string $currency = null, ?float $amount = null)
    {
        $this->status = $status;
        $this->displayName = $displayName;
        $this->currency = $currency;
        $this->amount = $amount;
    }
}