<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** New status for the invoice */
enum UpdateInvoiceStatusRequest: string
{
    case Paid = 'paid';
    case Canceled = 'canceled';
    case Unpaid = 'unpaid';
    case Scheduled = 'scheduled';
    case Draft = 'draft';
}
