<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class UpdateInboxItemRequestBody
{
    /**
     *
     * @var UpdateInboxItemStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\UpdateInboxItemStatus')]
    public UpdateInboxItemStatus $status;

    /**
     * @param  UpdateInboxItemStatus  $status
     * @phpstan-pure
     */
    public function __construct(UpdateInboxItemStatus $status)
    {
        $this->status = $status;
    }
}