<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** Status of the transaction. */
enum UpdateTransactionStatus: string
{
    case Pending = 'pending';
    case Archived = 'archived';
    case Completed = 'completed';
    case Posted = 'posted';
    case Excluded = 'excluded';
}
