<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** UpdateTransactionsMeta - Pagination metadata for the transactions response */
class UpdateTransactionsMeta
{
    /**
     * Whether there are more transactions available on the previous page
     *
     * @var bool $hasPreviousPage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasPreviousPage')]
    public bool $hasPreviousPage;

    /**
     * Whether there are more transactions available on the next page
     *
     * @var bool $hasNextPage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasNextPage')]
    public bool $hasNextPage;

    /**
     * Cursor for the next page of results, undefined if no more pages
     *
     * @var ?string $cursor
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('cursor')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $cursor = null;

    /**
     * @param  bool  $hasPreviousPage
     * @param  bool  $hasNextPage
     * @param  ?string  $cursor
     * @phpstan-pure
     */
    public function __construct(bool $hasPreviousPage, bool $hasNextPage, ?string $cursor = null)
    {
        $this->hasPreviousPage = $hasPreviousPage;
        $this->hasNextPage = $hasNextPage;
        $this->cursor = $cursor;
    }
}