<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class UpdateTeamByIdRequestBody
{
    /**
     * Name of the team or organization. Must be between 2 and 32 characters
     *
     * @var ?string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $name = null;

    /**
     * Primary contact email address for the team
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     * URL to the team's logo image. Must be hosted on midday.ai domain
     *
     * @var ?string $logoUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('logoUrl')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $logoUrl = null;

    /**
     * Base currency for the team in ISO 4217 format (3-letter currency code)
     *
     * @var ?string $baseCurrency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('baseCurrency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $baseCurrency = null;

    /**
     * @param  ?string  $name
     * @param  ?string  $email
     * @param  ?string  $logoUrl
     * @param  ?string  $baseCurrency
     * @phpstan-pure
     */
    public function __construct(?string $name = null, ?string $email = null, ?string $logoUrl = null, ?string $baseCurrency = null)
    {
        $this->name = $name;
        $this->email = $email;
        $this->logoUrl = $logoUrl;
        $this->baseCurrency = $baseCurrency;
    }
}