<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class UpdateTrackerProjectRequestBody
{
    /**
     * Name of the project
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Current status of the project
     *
     * @var ?UpdateTrackerProjectStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\UpdateTrackerProjectStatus|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateTrackerProjectStatus $status = null;

    /**
     * Detailed description of the project
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $description = null;

    /**
     * Estimated total hours required to complete the project
     *
     * @var ?float $estimate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('estimate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $estimate = null;

    /**
     * Hourly rate for the project in the specified currency
     *
     * @var ?float $rate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('rate')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $rate = null;

    /**
     * Currency code for the project rate in ISO 4217 format
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $currency = null;

    /**
     * Unique identifier of the customer associated with this project
     *
     * @var ?string $customerId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customerId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $customerId = null;

    /**
     * Array of tags to associate with the project
     *
     * @var ?array<UpdateTrackerProjectTag> $tags
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tags')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Operations\UpdateTrackerProjectTag>|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?array $tags = null;

    /**
     * Whether the project is billable to the customer
     *
     * @var ?bool $billable
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('billable')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $billable = null;

    /**
     * @param  string  $name
     * @param  ?UpdateTrackerProjectStatus  $status
     * @param  ?string  $description
     * @param  ?float  $estimate
     * @param  ?bool  $billable
     * @param  ?float  $rate
     * @param  ?string  $currency
     * @param  ?string  $customerId
     * @param  ?array<UpdateTrackerProjectTag>  $tags
     * @phpstan-pure
     */
    public function __construct(string $name, ?UpdateTrackerProjectStatus $status = null, ?string $description = null, ?float $estimate = null, ?float $rate = null, ?string $currency = null, ?string $customerId = null, ?array $tags = null, ?bool $billable = false)
    {
        $this->name = $name;
        $this->status = $status;
        $this->description = $description;
        $this->estimate = $estimate;
        $this->rate = $rate;
        $this->currency = $currency;
        $this->customerId = $customerId;
        $this->tags = $tags;
        $this->billable = $billable;
    }
}