<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** UpdateInvoiceRequestBody - Schema for updating an invoice */
class UpdateInvoiceRequestBody
{
    /**
     * New status for the invoice
     *
     * @var ?UpdateInvoiceStatusRequest $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\UpdateInvoiceStatusRequest|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?UpdateInvoiceStatusRequest $status = null;

    /**
     * Timestamp when the invoice was paid (ISO 8601)
     *
     * @var ?\DateTime $paidAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('paidAt')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?\DateTime $paidAt = null;

    /**
     * Internal note for the invoice
     *
     * @var ?string $internalNote
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('internalNote')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $internalNote = null;

    /**
     * @param  ?UpdateInvoiceStatusRequest  $status
     * @param  ?\DateTime  $paidAt
     * @param  ?string  $internalNote
     * @phpstan-pure
     */
    public function __construct(?UpdateInvoiceStatusRequest $status = null, ?\DateTime $paidAt = null, ?string $internalNote = null)
    {
        $this->status = $status;
        $this->paidAt = $paidAt;
        $this->internalNote = $internalNote;
    }
}