<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class UpdateTagRequestBody
{
    /**
     * The new name of the tag.
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * @param  string  $name
     * @phpstan-pure
     */
    public function __construct(string $name)
    {
        $this->name = $name;
    }
}