<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


/** Recurring frequency of the transaction. */
enum UpdateTransactionFrequency: string
{
    case Weekly = 'weekly';
    case Monthly = 'monthly';
    case Annually = 'annually';
    case Irregular = 'irregular';
}
