<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;

use Midday\Midday\Utils\SpeakeasyMetadata;
class UpdateNotificationStatusRequest
{
    /**
     *
     * @var string $notificationId
     */
    #[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=notificationId')]
    public string $notificationId;

    /**
     *
     * @var ?UpdateNotificationStatusRequestBody $requestBody
     */
    #[SpeakeasyMetadata('request:mediaType=application/json')]
    public ?UpdateNotificationStatusRequestBody $requestBody = null;

    /**
     * @param  string  $notificationId
     * @param  ?UpdateNotificationStatusRequestBody  $requestBody
     * @phpstan-pure
     */
    public function __construct(string $notificationId, ?UpdateNotificationStatusRequestBody $requestBody = null)
    {
        $this->notificationId = $notificationId;
        $this->requestBody = $requestBody;
    }
}