<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Operations;


class UpdateCurrentUserRequest
{
    /**
     * Full name of the user. Must be between 2 and 32 characters
     *
     * @var ?string $fullName
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('fullName')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $fullName = null;

    /**
     * Unique identifier of the team the user belongs to
     *
     * @var ?string $teamId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('teamId')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $teamId = null;

    /**
     * Email address of the user
     *
     * @var ?string $email
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('email')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $email = null;

    /**
     * URL to the user's avatar image. Must be hosted on midday.ai domain
     *
     * @var ?string $avatarUrl
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('avatarUrl')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $avatarUrl = null;

    /**
     * User's preferred locale for internationalization (language and region)
     *
     * @var ?string $locale
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('locale')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $locale = null;

    /**
     * Whether the user's calendar week starts on Monday (true) or Sunday (false)
     *
     * @var ?bool $weekStartsOnMonday
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('weekStartsOnMonday')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?bool $weekStartsOnMonday = null;

    /**
     * User's timezone identifier in IANA Time Zone Database format
     *
     * @var ?string $timezone
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timezone')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?string $timezone = null;

    /**
     * User's preferred time format: 12 for 12-hour format, 24 for 24-hour format
     *
     * @var ?float $timeFormat
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('timeFormat')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?float $timeFormat = null;

    /**
     * User's preferred date format. Available options: 'dd/MM/yyyy', 'MM/dd/yyyy', 'yyyy-MM-dd', 'dd.MM.yyyy'
     *
     * @var ?DateFormatRequest $dateFormat
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('dateFormat')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Operations\DateFormatRequest|null')]
    #[\Speakeasy\Serializer\Annotation\SkipWhenNull]
    public ?DateFormatRequest $dateFormat = null;

    /**
     * @param  ?string  $fullName
     * @param  ?string  $teamId
     * @param  ?string  $email
     * @param  ?string  $avatarUrl
     * @param  ?string  $locale
     * @param  ?bool  $weekStartsOnMonday
     * @param  ?string  $timezone
     * @param  ?float  $timeFormat
     * @param  ?DateFormatRequest  $dateFormat
     * @phpstan-pure
     */
    public function __construct(?string $fullName = null, ?string $teamId = null, ?string $email = null, ?string $avatarUrl = null, ?string $locale = null, ?bool $weekStartsOnMonday = null, ?string $timezone = null, ?float $timeFormat = null, ?DateFormatRequest $dateFormat = null)
    {
        $this->fullName = $fullName;
        $this->teamId = $teamId;
        $this->email = $email;
        $this->avatarUrl = $avatarUrl;
        $this->locale = $locale;
        $this->weekStartsOnMonday = $weekStartsOnMonday;
        $this->timezone = $timezone;
        $this->timeFormat = $timeFormat;
        $this->dateFormat = $dateFormat;
    }
}