<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


/** Account - Bank account information associated with the transaction */
class Account
{
    /**
     * Unique identifier of the bank account
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Display name of the bank account
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Currency of the bank account in ISO 4217 format
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * Bank connection information associated with the account
     *
     * @var Connection $connection
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('connection')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\Connection')]
    public Connection $connection;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  string  $currency
     * @param  Connection  $connection
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, string $currency, Connection $connection)
    {
        $this->id = $id;
        $this->name = $name;
        $this->currency = $currency;
        $this->connection = $connection;
    }
}