<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class Attachment
{
    /**
     * Unique identifier of the attachment
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Array of path segments for the attachment file storage location
     *
     * @var array<string> $path
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('path')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string>')]
    public array $path;

    /**
     * Size of the attachment file in bytes
     *
     * @var float $size
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('size')]
    public float $size;

    /**
     * MIME type of the attachment file
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * Original filename of the attachment when uploaded
     *
     * @var ?string $filename
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('filename')]
    public ?string $filename;

    /**
     * @param  string  $id
     * @param  array<string>  $path
     * @param  float  $size
     * @param  string  $type
     * @param  ?string  $filename
     * @phpstan-pure
     */
    public function __construct(string $id, array $path, float $size, string $type, ?string $filename = null)
    {
        $this->id = $id;
        $this->path = $path;
        $this->size = $size;
        $this->type = $type;
        $this->filename = $filename;
    }
}