<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


/** Category - Category information assigned to the transaction for organization */
class Category
{
    /**
     * Unique identifier of the category
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Display name of the category
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Hex color code associated with the category for UI display
     *
     * @var string $color
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('color')]
    public string $color;

    /**
     * URL-friendly slug of the category
     *
     * @var string $slug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('slug')]
    public string $slug;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  string  $color
     * @param  string  $slug
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, string $color, string $slug)
    {
        $this->id = $id;
        $this->name = $name;
        $this->color = $color;
        $this->slug = $slug;
    }
}