<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


/** Customer - Customer information associated with the project */
class Customer
{
    /**
     * Unique identifier of the customer
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Name of the customer or organization
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Website URL of the customer
     *
     * @var string $website
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('website')]
    public string $website;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  string  $website
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, string $website)
    {
        $this->id = $id;
        $this->name = $name;
        $this->website = $website;
    }
}