<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class ExpensesResultArray
{
    /**
     * Date for the expense value
     *
     * @var string $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public string $date;

    /**
     * Expense value for the given date
     *
     * @var float $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public float $value;

    /**
     * Currency code (ISO 4217)
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * Recurring expense value for the given date
     *
     * @var float $recurring
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('recurring')]
    public float $recurring;

    /**
     * Total expense for the given date
     *
     * @var float $total
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('total')]
    public float $total;

    /**
     * @param  string  $date
     * @param  float  $value
     * @param  string  $currency
     * @param  float  $recurring
     * @param  float  $total
     * @phpstan-pure
     */
    public function __construct(string $date, float $value, string $currency, float $recurring, float $total)
    {
        $this->date = $date;
        $this->value = $value;
        $this->currency = $currency;
        $this->recurring = $recurring;
        $this->total = $total;
    }
}