<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class GetExpensesResponseSchemaMeta
{
    /**
     * Type of metric
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * Currency code (ISO 4217)
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * @param  string  $type
     * @param  string  $currency
     * @phpstan-pure
     */
    public function __construct(string $type, string $currency)
    {
        $this->type = $type;
        $this->currency = $currency;
    }
}