<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class GetExpensesResponseSchema
{
    /**
     *
     * @var Summary $summary
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('summary')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\Summary')]
    public Summary $summary;

    /**
     *
     * @var GetExpensesResponseSchemaMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\GetExpensesResponseSchemaMeta')]
    public GetExpensesResponseSchemaMeta $meta;

    /**
     * $result
     *
     * @var array<ExpensesResultArray> $result
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('result')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Components\ExpensesResultArray>')]
    public array $result;

    /**
     * @param  Summary  $summary
     * @param  GetExpensesResponseSchemaMeta  $meta
     * @param  array<ExpensesResultArray>  $result
     * @phpstan-pure
     */
    public function __construct(Summary $summary, GetExpensesResponseSchemaMeta $meta, array $result)
    {
        $this->summary = $summary;
        $this->meta = $meta;
        $this->result = $result;
    }
}