<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class GetProfitResponseSchema
{
    /**
     *
     * @var ProfitSummary $summary
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('summary')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\ProfitSummary')]
    public ProfitSummary $summary;

    /**
     *
     * @var ProfitMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\ProfitMeta')]
    public ProfitMeta $meta;

    /**
     * $result
     *
     * @var array<ProfitResultItem> $result
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('result')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Components\ProfitResultItem>')]
    public array $result;

    /**
     * @param  ProfitSummary  $summary
     * @param  ProfitMeta  $meta
     * @param  array<ProfitResultItem>  $result
     * @phpstan-pure
     */
    public function __construct(ProfitSummary $summary, ProfitMeta $meta, array $result)
    {
        $this->summary = $summary;
        $this->meta = $meta;
        $this->result = $result;
    }
}