<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class GetRevenueResponseSchema
{
    /**
     *
     * @var RevenueSummary $summary
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('summary')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\RevenueSummary')]
    public RevenueSummary $summary;

    /**
     *
     * @var RevenueMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\RevenueMeta')]
    public RevenueMeta $meta;

    /**
     * $result
     *
     * @var array<RevenueResultItem> $result
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('result')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Components\RevenueResultItem>')]
    public array $result;

    /**
     * @param  RevenueSummary  $summary
     * @param  RevenueMeta  $meta
     * @param  array<RevenueResultItem>  $result
     * @phpstan-pure
     */
    public function __construct(RevenueSummary $summary, RevenueMeta $meta, array $result)
    {
        $this->summary = $summary;
        $this->meta = $meta;
        $this->result = $result;
    }
}