<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class NotificationResponseSchema
{
    /**
     *
     * @var NotificationSchema $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\NotificationSchema')]
    public NotificationSchema $data;

    /**
     * @param  NotificationSchema  $data
     * @phpstan-pure
     */
    public function __construct(NotificationSchema $data)
    {
        $this->data = $data;
    }
}