<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class NotificationSchema
{
    /**
     * Unique identifier of the notification
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * ISO timestamp when the notification was created
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     * Unique identifier of the team
     *
     * @var string $teamId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('teamId')]
    public string $teamId;

    /**
     * Type of notification
     *
     * @var string $type
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('type')]
    public string $type;

    /**
     * Priority level of the notification (1-3 = user notifications, 4-10 = insights)
     *
     * @var int $priority
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('priority')]
    public int $priority;

    /**
     * Source of the notification
     *
     * @var Source $source
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('source')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\Source')]
    public Source $source;

    /**
     * Current status of the notification
     *
     * @var NotificationSchemaStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\NotificationSchemaStatus')]
    public NotificationSchemaStatus $status;

    /**
     * Additional metadata for the notification
     *
     * @var array<string, mixed> $metadata
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('metadata')]
    #[\Speakeasy\Serializer\Annotation\Type('array<string, mixed>')]
    public array $metadata;

    /**
     * Unique identifier of the user (if applicable)
     *
     * @var ?string $userId
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('userId')]
    public ?string $userId;

    /**
     * ISO timestamp when the notification was last used by the system
     *
     * @var ?string $lastUsedAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('lastUsedAt')]
    public ?string $lastUsedAt;

    /**
     * @param  string  $id
     * @param  string  $createdAt
     * @param  string  $teamId
     * @param  string  $type
     * @param  int  $priority
     * @param  Source  $source
     * @param  NotificationSchemaStatus  $status
     * @param  array<string, mixed>  $metadata
     * @param  ?string  $userId
     * @param  ?string  $lastUsedAt
     * @phpstan-pure
     */
    public function __construct(string $id, string $createdAt, string $teamId, string $type, int $priority, Source $source, NotificationSchemaStatus $status, array $metadata, ?string $userId = null, ?string $lastUsedAt = null)
    {
        $this->id = $id;
        $this->createdAt = $createdAt;
        $this->teamId = $teamId;
        $this->type = $type;
        $this->priority = $priority;
        $this->source = $source;
        $this->status = $status;
        $this->metadata = $metadata;
        $this->userId = $userId;
        $this->lastUsedAt = $lastUsedAt;
    }
}