<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


/** Current status of the notification */
enum NotificationSchemaStatus: string
{
    case Unread = 'unread';
    case Read = 'read';
    case Archived = 'archived';
}
