<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class NotificationsResponseSchema
{
    /**
     * Array of notifications
     *
     * @var array<NotificationSchema> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Components\NotificationSchema>')]
    public array $data;

    /**
     * Pagination metadata
     *
     * @var NotificationsResponseSchemaMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\NotificationsResponseSchemaMeta')]
    public NotificationsResponseSchemaMeta $meta;

    /**
     * @param  array<NotificationSchema>  $data
     * @param  NotificationsResponseSchemaMeta  $meta
     * @phpstan-pure
     */
    public function __construct(array $data, NotificationsResponseSchemaMeta $meta)
    {
        $this->data = $data;
        $this->meta = $meta;
    }
}