<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class ProfitResultItem
{
    /**
     * Date for the metric (ISO 8601)
     *
     * @var string $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public string $date;

    /**
     *
     * @var ProfitPercentage $precentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('precentage')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\ProfitPercentage')]
    public ProfitPercentage $precentage;

    /**
     *
     * @var ProfitCurrent $current
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('current')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\ProfitCurrent')]
    public ProfitCurrent $current;

    /**
     *
     * @var ProfitPrevious $previous
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('previous')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\ProfitPrevious')]
    public ProfitPrevious $previous;

    /**
     * @param  string  $date
     * @param  ProfitPercentage  $precentage
     * @param  ProfitCurrent  $current
     * @param  ProfitPrevious  $previous
     * @phpstan-pure
     */
    public function __construct(string $date, ProfitPercentage $precentage, ProfitCurrent $current, ProfitPrevious $previous)
    {
        $this->date = $date;
        $this->precentage = $precentage;
        $this->current = $current;
        $this->previous = $previous;
    }
}