<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class ProfitSummary
{
    /**
     * Total profit for the current period
     *
     * @var float $currentTotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currentTotal')]
    public float $currentTotal;

    /**
     * Total profit for the previous period
     *
     * @var float $prevTotal
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('prevTotal')]
    public float $prevTotal;

    /**
     * Currency code (ISO 4217)
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * @param  float  $currentTotal
     * @param  float  $prevTotal
     * @param  string  $currency
     * @phpstan-pure
     */
    public function __construct(float $currentTotal, float $prevTotal, string $currency)
    {
        $this->currentTotal = $currentTotal;
        $this->prevTotal = $prevTotal;
        $this->currency = $currency;
    }
}