<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class ProfitPercentage
{
    /**
     * Percentage change compared to previous period
     *
     * @var float $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public float $value;

    /**
     * Status of the change
     *
     * @var ProfitPercentageStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\ProfitPercentageStatus')]
    public ProfitPercentageStatus $status;

    /**
     * @param  float  $value
     * @param  ProfitPercentageStatus  $status
     * @phpstan-pure
     */
    public function __construct(float $value, ProfitPercentageStatus $status)
    {
        $this->value = $value;
        $this->status = $status;
    }
}