<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


/** Status of the change */
enum RevenuePercentageStatus: string
{
    case Negative = 'negative';
    case Positive = 'positive';
}
