<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class RevenueCurrent
{
    /**
     * Date for the current value
     *
     * @var string $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public string $date;

    /**
     * Current value
     *
     * @var float $value
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('value')]
    public float $value;

    /**
     * Currency code (ISO 4217)
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * @param  string  $date
     * @param  float  $value
     * @param  string  $currency
     * @phpstan-pure
     */
    public function __construct(string $date, float $value, string $currency)
    {
        $this->date = $date;
        $this->value = $value;
        $this->currency = $currency;
    }
}