<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


/** Type of metric */
enum RevenueMetaType: string
{
    case Revenue = 'revenue';
}
