<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class RevenueResultItem
{
    /**
     * Date for the metric (ISO 8601)
     *
     * @var string $date
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('date')]
    public string $date;

    /**
     *
     * @var RevenuePercentage $percentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('percentage')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\RevenuePercentage')]
    public RevenuePercentage $percentage;

    /**
     *
     * @var RevenueCurrent $current
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('current')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\RevenueCurrent')]
    public RevenueCurrent $current;

    /**
     *
     * @var RevenuePrevious $previous
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('previous')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\RevenuePrevious')]
    public RevenuePrevious $previous;

    /**
     * @param  string  $date
     * @param  RevenuePercentage  $percentage
     * @param  RevenueCurrent  $current
     * @param  RevenuePrevious  $previous
     * @phpstan-pure
     */
    public function __construct(string $date, RevenuePercentage $percentage, RevenueCurrent $current, RevenuePrevious $previous)
    {
        $this->date = $date;
        $this->percentage = $percentage;
        $this->current = $current;
        $this->previous = $previous;
    }
}