<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;

use Midday\Midday\Utils\SpeakeasyMetadata;
class Security
{
    /**
     *
     * @var string $token
     */
    #[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer,name=Authorization')]
    public string $token;

    /**
     * @param  string  $token
     * @phpstan-pure
     */
    public function __construct(string $token)
    {
        $this->token = $token;
    }
}