<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;

use Midday\Midday\Utils\SpeakeasyMetadata;
class Security
{
    /**
     *
     * @var ?string $oauth2
     */
    #[SpeakeasyMetadata('security:scheme=true,type=apiKey,subtype=header,name=Authorization')]
    public ?string $oauth2 = null;

    /**
     *
     * @var ?string $token
     */
    #[SpeakeasyMetadata('security:scheme=true,type=http,subtype=bearer,name=Authorization')]
    public ?string $token = null;

    /**
     * @param  ?string  $oauth2
     * @param  ?string  $token
     * @phpstan-pure
     */
    public function __construct(?string $oauth2 = null, ?string $token = null)
    {
        $this->oauth2 = $oauth2;
        $this->token = $token;
    }
}