<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class SpendingResultArray
{
    /**
     * Spending category name
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Spending category slug
     *
     * @var string $slug
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('slug')]
    public string $slug;

    /**
     * Amount spent in this category
     *
     * @var float $amount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('amount')]
    public float $amount;

    /**
     * Currency code (ISO 4217)
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * Color code for the category
     *
     * @var string $color
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('color')]
    public string $color;

    /**
     * Percentage of total spending for this category
     *
     * @var float $percentage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('percentage')]
    public float $percentage;

    /**
     * @param  string  $name
     * @param  string  $slug
     * @param  float  $amount
     * @param  string  $currency
     * @param  string  $color
     * @param  float  $percentage
     * @phpstan-pure
     */
    public function __construct(string $name, string $slug, float $amount, string $currency, string $color, float $percentage)
    {
        $this->name = $name;
        $this->slug = $slug;
        $this->amount = $amount;
        $this->currency = $currency;
        $this->color = $color;
        $this->percentage = $percentage;
    }
}