<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class Summary
{
    /**
     * Average expense over the period
     *
     * @var float $averageExpense
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('averageExpense')]
    public float $averageExpense;

    /**
     * Currency code (ISO 4217)
     *
     * @var string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public string $currency;

    /**
     * @param  float  $averageExpense
     * @param  string  $currency
     * @phpstan-pure
     */
    public function __construct(float $averageExpense, string $currency)
    {
        $this->averageExpense = $averageExpense;
        $this->currency = $currency;
    }
}