<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class TagsResponse
{
    /**
     * List of tags.
     *
     * @var array<TagResponse> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Components\TagResponse>')]
    public array $data;

    /**
     * @param  array<TagResponse>  $data
     * @phpstan-pure
     */
    public function __construct(array $data)
    {
        $this->data = $data;
    }
}