<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class TrackerProjectResponse
{
    /**
     * Unique identifier of the project
     *
     * @var string $id
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('id')]
    public string $id;

    /**
     * Name of the project
     *
     * @var string $name
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('name')]
    public string $name;

    /**
     * Current status of the project
     *
     * @var TrackerProjectResponseStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\TrackerProjectResponseStatus')]
    public TrackerProjectResponseStatus $status;

    /**
     * Date and time when the project was created in ISO 8601 format
     *
     * @var string $createdAt
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('createdAt')]
    public string $createdAt;

    /**
     * Total monetary amount earned from the project
     *
     * @var float $totalAmount
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalAmount')]
    public float $totalAmount;

    /**
     * Array of tags associated with the project
     *
     * @var array<TrackerProjectResponseTag> $tags
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('tags')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Components\TrackerProjectResponseTag>')]
    public array $tags;

    /**
     * Detailed description of the project
     *
     * @var ?string $description
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('description')]
    public ?string $description;

    /**
     * Estimated total hours required to complete the project
     *
     * @var ?float $estimate
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('estimate')]
    public ?float $estimate;

    /**
     * Currency code for the project rate in ISO 4217 format
     *
     * @var ?string $currency
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('currency')]
    public ?string $currency;

    /**
     * Total tracked time for the project in seconds
     *
     * @var ?float $totalDuration
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('totalDuration')]
    public ?float $totalDuration;

    /**
     * Customer information associated with the project
     *
     * @var ?Customer $customer
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('customer')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\Customer|null')]
    public ?Customer $customer;

    /**
     * Array of users assigned to work on the project
     *
     * @var ?array<User> $users
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('users')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Components\User>|null')]
    public ?array $users;

    /**
     * @param  string  $id
     * @param  string  $name
     * @param  TrackerProjectResponseStatus  $status
     * @param  string  $createdAt
     * @param  float  $totalAmount
     * @param  array<TrackerProjectResponseTag>  $tags
     * @param  ?string  $description
     * @param  ?float  $estimate
     * @param  ?string  $currency
     * @param  ?float  $totalDuration
     * @param  ?Customer  $customer
     * @param  ?array<User>  $users
     * @phpstan-pure
     */
    public function __construct(string $id, string $name, TrackerProjectResponseStatus $status, string $createdAt, float $totalAmount, array $tags, ?string $description = null, ?float $estimate = null, ?string $currency = null, ?float $totalDuration = null, ?Customer $customer = null, ?array $users = null)
    {
        $this->id = $id;
        $this->name = $name;
        $this->status = $status;
        $this->createdAt = $createdAt;
        $this->totalAmount = $totalAmount;
        $this->tags = $tags;
        $this->description = $description;
        $this->estimate = $estimate;
        $this->currency = $currency;
        $this->totalDuration = $totalDuration;
        $this->customer = $customer;
        $this->users = $users;
    }
}