<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class TrackerProjectsResponse
{
    /**
     * Pagination metadata for the projects response
     *
     * @var TrackerProjectsResponseMeta $meta
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('meta')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\TrackerProjectsResponseMeta')]
    public TrackerProjectsResponseMeta $meta;

    /**
     * Array of tracker projects matching the query criteria
     *
     * @var array<TrackerProjectResponse> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Components\TrackerProjectResponse>')]
    public array $data;

    /**
     * @param  TrackerProjectsResponseMeta  $meta
     * @param  array<TrackerProjectResponse>  $data
     * @phpstan-pure
     */
    public function __construct(TrackerProjectsResponseMeta $meta, array $data)
    {
        $this->meta = $meta;
        $this->data = $data;
    }
}