<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


/** TrackerProjectsResponseMeta - Pagination metadata for the projects response */
class TrackerProjectsResponseMeta
{
    /**
     * Whether there are more projects available on the next page
     *
     * @var bool $hasNextPage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasNextPage')]
    public bool $hasNextPage;

    /**
     * Whether there are more projects available on the previous page
     *
     * @var bool $hasPreviousPage
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('hasPreviousPage')]
    public bool $hasPreviousPage;

    /**
     * @param  bool  $hasNextPage
     * @param  bool  $hasPreviousPage
     * @phpstan-pure
     */
    public function __construct(bool $hasNextPage, bool $hasPreviousPage)
    {
        $this->hasNextPage = $hasNextPage;
        $this->hasPreviousPage = $hasPreviousPage;
    }
}