<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


/** The new status to apply to all notifications for the authenticated user */
enum UpdateAllNotificationsStatusSchemaStatus: string
{
    case Unread = 'unread';
    case Read = 'read';
    case Archived = 'archived';
}
