<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class UpdateAllNotificationsStatusResponseSchema
{
    /**
     * Array of updated notifications
     *
     * @var array<NotificationSchema> $data
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('data')]
    #[\Speakeasy\Serializer\Annotation\Type('array<\Midday\Midday\Models\Components\NotificationSchema>')]
    public array $data;

    /**
     * @param  array<NotificationSchema>  $data
     * @phpstan-pure
     */
    public function __construct(array $data)
    {
        $this->data = $data;
    }
}