<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday\Models\Components;


class UpdateAllNotificationsStatusSchema
{
    /**
     * The new status to apply to all notifications for the authenticated user
     *
     * @var UpdateAllNotificationsStatusSchemaStatus $status
     */
    #[\Speakeasy\Serializer\Annotation\SerializedName('status')]
    #[\Speakeasy\Serializer\Annotation\Type('\Midday\Midday\Models\Components\UpdateAllNotificationsStatusSchemaStatus')]
    public UpdateAllNotificationsStatusSchemaStatus $status;

    /**
     * @param  UpdateAllNotificationsStatusSchemaStatus  $status
     * @phpstan-pure
     */
    public function __construct(UpdateAllNotificationsStatusSchemaStatus $status)
    {
        $this->status = $status;
    }
}