<?php

/**
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

declare(strict_types=1);

namespace Midday\Midday;



/** Midday - Midday API: Midday is a platform for Invoicing, Time tracking, File reconciliation, Storage, Financial Overview & your own Assistant. */
class Midday
{
    public const SERVERS = [
        /** Production API */
        'https://api.midday.ai',
    ];

    public Transactions $transactions;

    public Teams $teams;

    public Users $users;

    public Customers $customers;

    public BankAccounts $bankAccounts;

    public Tags $tags;

    public Documents $documents;

    public Inbox $inbox;

    public Invoices $invoices;

    public Search $search;

    public Metrics $metrics;

    public TrackerProjects $trackerProjects;

    public TrackerEntries $trackerEntries;

    public TrackerTimer $trackerTimer;

    /**
     * Returns a new instance of the SDK builder used to configure and create the SDK instance.
     *
     * @return MiddayBuilder
     */
    public static function builder(): MiddayBuilder
    {
        return new MiddayBuilder();
    }

    /**
     * @param  SDKConfiguration  $sdkConfiguration
     */
    public function __construct(
        public SDKConfiguration $sdkConfiguration,
    ) {
        $this->transactions = new Transactions($this->sdkConfiguration);
        $this->teams = new Teams($this->sdkConfiguration);
        $this->users = new Users($this->sdkConfiguration);
        $this->customers = new Customers($this->sdkConfiguration);
        $this->bankAccounts = new BankAccounts($this->sdkConfiguration);
        $this->tags = new Tags($this->sdkConfiguration);
        $this->documents = new Documents($this->sdkConfiguration);
        $this->inbox = new Inbox($this->sdkConfiguration);
        $this->invoices = new Invoices($this->sdkConfiguration);
        $this->search = new Search($this->sdkConfiguration);
        $this->metrics = new Metrics($this->sdkConfiguration);
        $this->trackerProjects = new TrackerProjects($this->sdkConfiguration);
        $this->trackerEntries = new TrackerEntries($this->sdkConfiguration);
        $this->trackerTimer = new TrackerTimer($this->sdkConfiguration);
        $this->initHooks();

    }

    private function initHooks(): void
    {
        $this->sdkConfiguration = $this->sdkConfiguration->hooks->sdkInit($this->sdkConfiguration);
    }
}